hires = [{
    'Name': 'BSGA - 12/03/2024 ref 20405', 'Reference Number': '42834',
    'Booked Date': '20240208', 'Send Out Date': '20240312', 'Due Back Date': '20240321',
    'Status': 'Booked in', 'Actual Return Date': '', 'Purpose': 'trampoline event',
    'Closed': 'FALSE', 'Inv VHF Desc': '',
    'Delivery Address': 'C/o AAAsports\r\nShakespeare Street\r\nSunderland',
    'Number Sgl Charger': '0', 'Inv UHF Price': '12.00', 'Delivery Postcode': 'SR5 2JF',
    'Invoice': 'C:\\ProgramData\\Commence\\Commence\\8.0\\Data\\FILES\\a24679.docx',
    'Delivery Name': 'BSGA', 'Payment Terms': 'Paid by card thanks', 'Number VHF': '0',
    'Number EM': '6', 'Number VHF 6-way': '0', 'Number ICOM PSU': '0',
    'Inv UHF Desc': 'Hire of Kirisun UHF walkie-talkie', 'Inv VHF Price': '',
    'Inv EM Desc': 'Hire of earpiece/microphone', 'Number Megaphone': '0',
    'Delivery Contact': 'Andi Revell', 'Delivery Tel': '03335776787',
    'Send / Collect': 'We send and pick up',
    'Send Method': 'Parcelforce/DB and we collect',
    'Hire Sheet Text': '\r\n* 6 x Kirisun UHF radios\r\n\r\n* 1 x six-slot radio charger units\r\n\r\n* 6 x Earpiece/microphones (in re-usable bags)\r\n\r\n* 6 x Semi-covert earpiece/mics (in re-usable bags)\r\n\r\n* 1 x extra radio battery packs\r\n\r\n* 1 x Laminated walkie-talkie instruction sheet',
    'Special Kit': '', 'Return Notes': '', 'Number UHF': '6', 'Number UHF 6-way': '1',
    'Number Parrot': '0', 'Number Headset': '0', 'Delivery Ref': '',
    'Number Batteries': '1', 'Number Cases': '0', 'Delivery Description': '',
    'Inv EM Price': '1.00', 'Inv Batt Desc': 'Hire of spare battery pack',
    'Inv Batt Price': '1.00', 'Inv Parrot Desc': '', 'Inv Parrot Price': '',
    'Inv Headset Desc': '', 'Inv Headset Price': '', 'Inv Case Desc': '',
    'Inv Case Price': '', 'Inv Send Desc': 'Send Date',
    'Inv Delivery Desc': 'Delivery & Collection',
    'Inv Return Desc': 'Cust. to advise when ready for collection',
    'Delivery Cost': '35.00', 'Purchase Order': '', 'Inv EM Qty': '6',
    'Inv Headset Qty': '', 'Inv Parrot Qty': '', 'Inv Batt Qty': '1', 'Inv Case Qty': '',
    'Inv UHF Qty': '6', 'Inv VHF Qty': '', 'Discount Percentage': '25%',
    'Discount Description': 'Charity Discount', 'Instruc Walkies': 'TRUE',
    'Number Megaphone Bat': '0', 'Inv Mega Qty': '', 'Inv Mega Price': '',
    'Inv Mega Desc': '', 'Inv Charger Desc': 'Radio chargers included in price',
    'Inv Meg Batt Desc': '', 'Instruc Megaphone': 'FALSE', 'Instruc Icom': 'FALSE',
    'Number Icom': '0', 'Reprogrammed': 'FALSE', 'Inv Icom Desc': '', 'Inv Icom Qty': '',
    'Inv Icom Price': '', 'Megaphone charger': 'FALSE',
    'Delivery Email': 'andi.revell@aaasports.co.uk', 'Packed By': '', 'Unpacked by': '',
    'Number EMC': '6', 'Number Headset Big': '0',
    'Inv EMC Desc': 'Hire of semi-covert earpiece/mic', 'Inv EMC Price': '2.00',
    'Inv EMC Qty': '6', 'Inv Bighead Desc': '', 'Inv Bighead Price': '',
    'Inv Bighead Qty': '', 'Number ICOM Car Lead': '0', 'Weeks': '1', 'Boxes': '1',
    'Inv Purchase Order': '', 'Number Magmount': '0', 'Pickup Arranged': 'FALSE',
    'Number Clipon Aerial': '0', 'Recurring Hire': 'FALSE', 'Radio Type': 'Kirisun UHF',
    'Inv Wand Desc': '', 'Inv Wand Price': '', 'Inv Wand Qty': '', 'Number Wand': '0',
    'Number Repeater': '0', 'DB label printed': 'FALSE',
    'All Address': 'Andi Revell\r\nBSGA\r\nC/o AAAsports\r\nShakespeare Street\r\nSunderland\r\nSR5 2JF\r\n\r\n03335776787\r\n\r\nandi.revell@aaasports.co.uk',
    'Bar Codes': '', 'Sending Status': 'Fine no problem',
    'Inv Booked Date': 'Thu 8 February 2024', 'Inv Send Out Date': 'Tue 12 March 2024',
    'Inv Due Back Date': 'Thu 21 March 2024', 'Number Wand Battery': '0',
    'Number Wand Charger': '0', 'Number Aerial Adapt': '0', 'Packed Date': '',
    'Packed Time': '', 'Unpacked Date': '', 'Unpacked Time': '',
    'Hire Sheet Printed': 'FALSE', 'ShipMe': 'FALSE', 'Missing Kit': '', 'Outbound ID': '',
    'PreShip Emailed': 'FALSE', 'To Customer': 'BSGA', 'Has document Log': '',
    'Involves Equipment': '', 'Inbound ID': ''
}, {
    'Name': 'Festival Republic Limited Crystal Palace ref 31877',
    'Reference Number': '42930', 'Booked Date': '20240207', 'Send Out Date': '20240703',
    'Due Back Date': '20240708', 'Status': 'Booked in', 'Actual Return Date': '',
    'Purpose': 'Live Nation (Music) UK Limited\r\nFarmiloe Building\r\n30 St John Street\r\nLondon\r\nEC1M 4AY\r\n\r\n\r\n40 units\r\n\r\n \r\n\r\nDelivery date – 3 rd July\r\n\r\nCollection – 8 th July\r\n\r\n \r\n',
    'Closed': 'FALSE', 'Inv VHF Desc': '',
    'Delivery Address': 'Blue Gate via Anerley Hill Gate\r\nCrystal Palace Park\r\nCrystal Palace\r\nLondon',
    'Number Sgl Charger': '0', 'Inv UHF Price': '', 'Delivery Postcode': 'SE19 2AD',
    'Invoice': 'C:\\ProgramData\\Commence\\Commence\\8.0\\Data\\FILES\\A24672.docx',
    'Delivery Name': 'Festival Republic Limited',
    'Payment Terms': 'To be paid before hire date', 'Number VHF': '0', 'Number EM': '0',
    'Number VHF 6-way': '0', 'Number ICOM PSU': '0', 'Inv UHF Desc': '',
    'Inv VHF Price': '', 'Inv EM Desc': '', 'Number Megaphone': '0',
    'Delivery Contact': 'Simona Alfarano', 'Delivery Tel': '07448 055731',
    'Send / Collect': 'We send and pick up', 'Send Method': 'RUSH car/van',
    'Hire Sheet Text': '\r\n\r\n* 25 x metal detector wands\r\n\r\n* 35 x metal detector wand batteries\r\n\r\n* 3 x metal detector battery chargers',
    'Special Kit': '', 'Return Notes': '', 'Number UHF': '0', 'Number UHF 6-way': '0',
    'Number Parrot': '0', 'Number Headset': '0', 'Delivery Ref': '',
    'Number Batteries': '0', 'Number Cases': '0', 'Delivery Description': '',
    'Inv EM Price': '', 'Inv Batt Desc': '', 'Inv Batt Price': '', 'Inv Parrot Desc': '',
    'Inv Parrot Price': '', 'Inv Headset Desc': '', 'Inv Headset Price': '',
    'Inv Case Desc': '', 'Inv Case Price': '', 'Inv Send Desc': 'Send Date',
    'Inv Delivery Desc': 'Delivery & Collection',
    'Inv Return Desc': 'Cust. to advise when ready for collection',
    'Delivery Cost': '90.00', 'Purchase Order': '', 'Inv EM Qty': '',
    'Inv Headset Qty': '', 'Inv Parrot Qty': '', 'Inv Batt Qty': '', 'Inv Case Qty': '',
    'Inv UHF Qty': '', 'Inv VHF Qty': '', 'Discount Percentage': '',
    'Discount Description': '', 'Instruc Walkies': 'FALSE', 'Number Megaphone Bat': '0',
    'Inv Mega Qty': '', 'Inv Mega Price': '', 'Inv Mega Desc': '', 'Inv Charger Desc': '',
    'Inv Meg Batt Desc': '', 'Instruc Megaphone': 'FALSE', 'Instruc Icom': 'FALSE',
    'Number Icom': '0', 'Reprogrammed': 'FALSE', 'Inv Icom Desc': '', 'Inv Icom Qty': '',
    'Inv Icom Price': '', 'Megaphone charger': 'FALSE',
    'Delivery Email': 'salfarano@festivalrepublic.com', 'Packed By': '', 'Unpacked by': '',
    'Number EMC': '0', 'Number Headset Big': '0', 'Inv EMC Desc': '', 'Inv EMC Price': '',
    'Inv EMC Qty': '', 'Inv Bighead Desc': '', 'Inv Bighead Price': '',
    'Inv Bighead Qty': '', 'Number ICOM Car Lead': '0', 'Weeks': '1', 'Boxes': '1',
    'Inv Purchase Order': '', 'Number Magmount': '0', 'Pickup Arranged': 'FALSE',
    'Number Clipon Aerial': '0', 'Recurring Hire': 'FALSE', 'Radio Type': 'not selected',
    'Inv Wand Desc': 'Hire of metal detector wands', 'Inv Wand Price': '5.00',
    'Inv Wand Qty': '25', 'Number Wand': '25', 'Number Repeater': '0',
    'DB label printed': 'FALSE',
    'All Address': 'Simona Alfarano\r\nFestival Republic Limited\r\nBlue Gate via Anerley Hill Gate\r\nCrystal Palace Park\r\nCrystal Palace\r\nLondon\r\nSE19 2AD\r\n\r\n07448 055731\r\n\r\nsalfarano@festivalrepublic.com',
    'Bar Codes': '', 'Sending Status': 'Fine no problem',
    'Inv Booked Date': 'Wed 7 February 2024', 'Inv Send Out Date': 'Wed 3 July 2024',
    'Inv Due Back Date': 'Mon 8 July 2024', 'Number Wand Battery': '35',
    'Number Wand Charger': '3', 'Number Aerial Adapt': '0', 'Packed Date': '',
    'Packed Time': '', 'Unpacked Date': '', 'Unpacked Time': '',
    'Hire Sheet Printed': 'FALSE', 'ShipMe': 'FALSE', 'Missing Kit': '', 'Outbound ID': '',
    'PreShip Emailed': 'FALSE', 'To Customer': 'Festival Republic Limited',
    'Has document Log': '', 'Involves Equipment': '', 'Inbound ID': ''
}, {
    'Name': 'Festival Republic Limited Gunnersbury ref 31879', 'Reference Number': '42931',
    'Booked Date': '20240207', 'Send Out Date': '20240807', 'Due Back Date': '20240819',
    'Status': 'Booked in', 'Actual Return Date': '', 'Purpose': '', 'Closed': 'FALSE',
    'Inv VHF Desc': '',
    'Delivery Address': 'Production Entrance (Blue Gate)\r\nGunnersbury Park\r\nLionel Road North/Popes Lane Entrance\r\nLondon',
    'Number Sgl Charger': '0', 'Inv UHF Price': '', 'Delivery Postcode': 'W5 4NS',
    'Invoice': 'C:\\ProgramData\\Commence\\Commence\\8.0\\Data\\FILES\\A24673.docx',
    'Delivery Name': 'Gunnersbury Live', 'Payment Terms': 'To be paid before hire date',
    'Number VHF': '0', 'Number EM': '0', 'Number VHF 6-way': '0', 'Number ICOM PSU': '0',
    'Inv UHF Desc': '', 'Inv VHF Price': '', 'Inv EM Desc': '', 'Number Megaphone': '0',
    'Delivery Contact': 'Simona Alfarano', 'Delivery Tel': '07448 055731',
    'Send / Collect': 'We send and pick up', 'Send Method': 'RUSH car/van',
    'Hire Sheet Text': '\r\n\r\n* 30 x metal detector wands\r\n\r\n* 45 x metal detector wand batteries\r\n\r\n* 3 x metal detector battery chargers\r\n\r\n* 1 x megaphone battery charger unit',
    'Special Kit': '', 'Return Notes': '', 'Number UHF': '0', 'Number UHF 6-way': '0',
    'Number Parrot': '0', 'Number Headset': '0', 'Delivery Ref': '',
    'Number Batteries': '0', 'Number Cases': '0', 'Delivery Description': '',
    'Inv EM Price': '', 'Inv Batt Desc': '', 'Inv Batt Price': '', 'Inv Parrot Desc': '',
    'Inv Parrot Price': '', 'Inv Headset Desc': '', 'Inv Headset Price': '',
    'Inv Case Desc': '', 'Inv Case Price': '', 'Inv Send Desc': 'Send Date',
    'Inv Delivery Desc': 'Delivery & Collection',
    'Inv Return Desc': 'Cust. to advise when ready for collection',
    'Delivery Cost': '50.00', 'Purchase Order': '', 'Inv EM Qty': '',
    'Inv Headset Qty': '', 'Inv Parrot Qty': '', 'Inv Batt Qty': '', 'Inv Case Qty': '',
    'Inv UHF Qty': '', 'Inv VHF Qty': '', 'Discount Percentage': '',
    'Discount Description': '', 'Instruc Walkies': 'FALSE', 'Number Megaphone Bat': '0',
    'Inv Mega Qty': '', 'Inv Mega Price': '', 'Inv Mega Desc': '', 'Inv Charger Desc': '',
    'Inv Meg Batt Desc': '', 'Instruc Megaphone': 'FALSE', 'Instruc Icom': 'FALSE',
    'Number Icom': '0', 'Reprogrammed': 'FALSE', 'Inv Icom Desc': '', 'Inv Icom Qty': '',
    'Inv Icom Price': '', 'Megaphone charger': 'TRUE',
    'Delivery Email': 'salfarano@festivalrepublic.com', 'Packed By': '', 'Unpacked by': '',
    'Number EMC': '0', 'Number Headset Big': '0', 'Inv EMC Desc': '', 'Inv EMC Price': '',
    'Inv EMC Qty': '', 'Inv Bighead Desc': '', 'Inv Bighead Price': '',
    'Inv Bighead Qty': '', 'Number ICOM Car Lead': '0', 'Weeks': '1', 'Boxes': '1',
    'Inv Purchase Order': '', 'Number Magmount': '0', 'Pickup Arranged': 'FALSE',
    'Number Clipon Aerial': '0', 'Recurring Hire': 'FALSE', 'Radio Type': 'not selected',
    'Inv Wand Desc': 'Hire of metal detector wands', 'Inv Wand Price': '5.00',
    'Inv Wand Qty': '30', 'Number Wand': '30', 'Number Repeater': '0',
    'DB label printed': 'FALSE',
    'All Address': 'Simona Alfarano\r\nGunnersbury Live\r\nProduction Entrance (Blue Gate)\r\nGunnersbury Park\r\nLionel Road North/Popes Lane Entrance\r\nLondon\r\nW5 4NS\r\n\r\n07448 055731\r\n\r\nsalfarano@festivalrepublic.com',
    'Bar Codes': '', 'Sending Status': 'Fine no problem',
    'Inv Booked Date': 'Wed 7 February 2024', 'Inv Send Out Date': 'Wed 7 August 2024',
    'Inv Due Back Date': 'Mon 19 August 2024', 'Number Wand Battery': '45',
    'Number Wand Charger': '3', 'Number Aerial Adapt': '0', 'Packed Date': '',
    'Packed Time': '', 'Unpacked Date': '', 'Unpacked Time': '',
    'Hire Sheet Printed': 'FALSE', 'ShipMe': 'FALSE', 'Missing Kit': '', 'Outbound ID': '',
    'PreShip Emailed': 'FALSE', 'To Customer': 'Festival Republic Limited',
    'Has document Log': '', 'Involves Equipment': '', 'Inbound ID': ''
}, {
    'Name': 'Greenwood Automotive - 19/02/2024 ref 20396', 'Reference Number': '42969',
    'Booked Date': '20240206', 'Send Out Date': '20240219', 'Due Back Date': '20240227',
    'Status': 'Booked in', 'Actual Return Date': '',
    'Purpose': 'for car convoy event 22/02', 'Closed': 'FALSE', 'Inv VHF Desc': '',
    'Delivery Address': 'Old Quarry Phlashetts Lane\r\nWell\r\nBedale',
    'Number Sgl Charger': '0', 'Inv UHF Price': '11.00', 'Delivery Postcode': 'DL8 2QH',
    'Invoice': 'C:\\ProgramData\\Commence\\Commence\\8.0\\Data\\FILES\\a24666.docx',
    'Delivery Name': 'Greenwood Automotive', 'Payment Terms': 'Due for payment please',
    'Number VHF': '0', 'Number EM': '0', 'Number VHF 6-way': '0', 'Number ICOM PSU': '0',
    'Inv UHF Desc': 'Hire of Hytera Digital walkie-talkie', 'Inv VHF Price': '',
    'Inv EM Desc': '', 'Number Megaphone': '0', 'Delivery Contact': 'Sam Greenwood',
    'Delivery Tel': '0', 'Send / Collect': 'We send and pick up',
    'Send Method': 'Parcelforce/DB and we collect',
    'Hire Sheet Text': '\r\n* 12 x Hytera Digital radios\r\n\r\n* 2 x six-slot radio charger units\r\n\r\n* 1 x Laminated walkie-talkie instruction sheet',
    'Special Kit': '', 'Return Notes': '', 'Number UHF': '12', 'Number UHF 6-way': '2',
    'Number Parrot': '0', 'Number Headset': '0', 'Delivery Ref': '',
    'Number Batteries': '0', 'Number Cases': '0', 'Delivery Description': '',
    'Inv EM Price': '', 'Inv Batt Desc': '', 'Inv Batt Price': '', 'Inv Parrot Desc': '',
    'Inv Parrot Price': '', 'Inv Headset Desc': '', 'Inv Headset Price': '',
    'Inv Case Desc': '', 'Inv Case Price': '', 'Inv Send Desc': 'Send Date',
    'Inv Delivery Desc': 'Delivery & Collection',
    'Inv Return Desc': 'Cust. to advise when ready for collection',
    'Delivery Cost': '35.00', 'Purchase Order': '', 'Inv EM Qty': '',
    'Inv Headset Qty': '', 'Inv Parrot Qty': '', 'Inv Batt Qty': '', 'Inv Case Qty': '',
    'Inv UHF Qty': '12', 'Inv VHF Qty': '', 'Discount Percentage': '',
    'Discount Description': '', 'Instruc Walkies': 'TRUE', 'Number Megaphone Bat': '0',
    'Inv Mega Qty': '', 'Inv Mega Price': '', 'Inv Mega Desc': '',
    'Inv Charger Desc': 'Radio chargers included in price', 'Inv Meg Batt Desc': '',
    'Instruc Megaphone': 'FALSE', 'Instruc Icom': 'FALSE', 'Number Icom': '0',
    'Reprogrammed': 'FALSE', 'Inv Icom Desc': '', 'Inv Icom Qty': '', 'Inv Icom Price': '',
    'Megaphone charger': 'FALSE', 'Delivery Email': 'sam@greenwoodautomotive.co.uk',
    'Packed By': '', 'Unpacked by': '', 'Number EMC': '0', 'Number Headset Big': '0',
    'Inv EMC Desc': '', 'Inv EMC Price': '', 'Inv EMC Qty': '', 'Inv Bighead Desc': '',
    'Inv Bighead Price': '', 'Inv Bighead Qty': '', 'Number ICOM Car Lead': '0',
    'Weeks': '1', 'Boxes': '1', 'Inv Purchase Order': '', 'Number Magmount': '0',
    'Pickup Arranged': 'FALSE', 'Number Clipon Aerial': '0', 'Recurring Hire': 'FALSE',
    'Radio Type': 'Hytera Digital', 'Inv Wand Desc': '', 'Inv Wand Price': '',
    'Inv Wand Qty': '', 'Number Wand': '0', 'Number Repeater': '0',
    'DB label printed': 'FALSE',
    'All Address': 'Sam Greenwood\r\nGreenwood Automotive\r\nOld Quarry Phlashetts Lane\r\nWell\r\nBedale\r\nDL8 2QH\r\n\r\n0\r\n\r\nsam@greenwoodautomotive.co.uk',
    'Bar Codes': '', 'Sending Status': 'Fine no problem',
    'Inv Booked Date': 'Tue 6 February 2024', 'Inv Send Out Date': 'Mon 19 February 2024',
    'Inv Due Back Date': 'Tue 27 February 2024', 'Number Wand Battery': '0',
    'Number Wand Charger': '0', 'Number Aerial Adapt': '0', 'Packed Date': '',
    'Packed Time': '', 'Unpacked Date': '', 'Unpacked Time': '',
    'Hire Sheet Printed': 'FALSE', 'ShipMe': 'FALSE', 'Missing Kit': '', 'Outbound ID': '',
    'PreShip Emailed': 'FALSE', 'To Customer': 'Greenwood Automotive',
    'Has document Log': '', 'Involves Equipment': '', 'Inbound ID': ''
}, {
    'Name': 'IAPS - 04/06/2024 ref 20376', 'Reference Number': '43004',
    'Booked Date': '20240125', 'Send Out Date': '20240604', 'Due Back Date': '20240613',
    'Status': 'Booked in', 'Actual Return Date': '', 'Purpose': 'dates may need changing',
    'Closed': 'FALSE', 'Inv VHF Desc': '',
    'Delivery Address': 'Bishop’s House\r\nArtemis Drive\r\nTachbrook Park\r\nWarwick',
    'Number Sgl Charger': '0', 'Inv UHF Price': '11.00', 'Delivery Postcode': 'CV34 6UD',
    'Invoice': 'C:\\ProgramData\\Commence\\Commence\\8.0\\Data\\FILES\\a24637.docx',
    'Delivery Name': 'IAPS', 'Payment Terms': 'To be paid before hire date',
    'Number VHF': '0', 'Number EM': '10', 'Number VHF 6-way': '0', 'Number ICOM PSU': '0',
    'Inv UHF Desc': 'Hire of Hytera Digital walkie-talkie', 'Inv VHF Price': '',
    'Inv EM Desc': 'Hire of earpiece/microphone', 'Number Megaphone': '2',
    'Delivery Contact': 'Emily Connell', 'Delivery Tel': '01926 461501',
    'Send / Collect': 'We send and pick up',
    'Send Method': 'Parcelforce/DB and we collect',
    'Hire Sheet Text': '\r\n* 10 x Hytera Digital radios\r\n\r\n* 2 x six-slot radio charger units\r\n\r\n* 10 x Earpiece/microphones (in re-usable bags)\r\n\r\n* 6 x leather cases with carry straps\r\n\r\n* 2 x headsets with boom mics\r\n\r\n* 2 x extra radio battery packs\r\n\r\n* 2 Megaphones\r\n\r\n* 4 sets of 8 rechargeable batteries\r\n\r\n* 1 x Laminated walkie-talkie instruction sheet\r\n\r\n* 1 x Laminated megaphone instruction sheet',
    'Special Kit': '', 'Return Notes': '', 'Number UHF': '10', 'Number UHF 6-way': '2',
    'Number Parrot': '0', 'Number Headset': '2', 'Delivery Ref': '',
    'Number Batteries': '2', 'Number Cases': '6', 'Delivery Description': '',
    'Inv EM Price': '1.00', 'Inv Batt Desc': 'Hire of spare battery pack',
    'Inv Batt Price': '1.00', 'Inv Parrot Desc': '', 'Inv Parrot Price': '',
    'Inv Headset Desc': 'Hire of headset', 'Inv Headset Price': '2.00',
    'Inv Case Desc': 'Hire of leather case with neck strap', 'Inv Case Price': '1.00',
    'Inv Send Desc': 'Send Date', 'Inv Delivery Desc': 'Delivery & Collection',
    'Inv Return Desc': 'Cust. to advise when ready for collection',
    'Delivery Cost': '35.00', 'Purchase Order': '', 'Inv EM Qty': '10',
    'Inv Headset Qty': '2', 'Inv Parrot Qty': '', 'Inv Batt Qty': '2', 'Inv Case Qty': '6',
    'Inv UHF Qty': '10', 'Inv VHF Qty': '', 'Discount Percentage': '',
    'Discount Description': '', 'Instruc Walkies': 'TRUE', 'Number Megaphone Bat': '4',
    'Inv Mega Qty': '2', 'Inv Mega Price': '16.00', 'Inv Mega Desc': 'Hire of megaphones',
    'Inv Charger Desc': 'Radio chargers included in price',
    'Inv Meg Batt Desc': '4 sets of 8 rechargeable batts included',
    'Instruc Megaphone': 'TRUE', 'Instruc Icom': 'FALSE', 'Number Icom': '0',
    'Reprogrammed': 'FALSE', 'Inv Icom Desc': '', 'Inv Icom Qty': '', 'Inv Icom Price': '',
    'Megaphone charger': 'FALSE', 'Delivery Email': 'ec@iaps.uk', 'Packed By': '',
    'Unpacked by': '', 'Number EMC': '0', 'Number Headset Big': '0', 'Inv EMC Desc': '',
    'Inv EMC Price': '', 'Inv EMC Qty': '', 'Inv Bighead Desc': '',
    'Inv Bighead Price': '', 'Inv Bighead Qty': '', 'Number ICOM Car Lead': '0',
    'Weeks': '1', 'Boxes': '1', 'Inv Purchase Order': '', 'Number Magmount': '0',
    'Pickup Arranged': 'FALSE', 'Number Clipon Aerial': '0', 'Recurring Hire': 'FALSE',
    'Radio Type': 'Hytera Digital', 'Inv Wand Desc': '', 'Inv Wand Price': '',
    'Inv Wand Qty': '', 'Number Wand': '0', 'Number Repeater': '0',
    'DB label printed': 'FALSE',
    'All Address': 'Emily Connell\r\nIAPS\r\nBishop’s House\r\nArtemis Drive\r\nTachbrook Park\r\nWarwick\r\nCV34 6UD\r\n\r\n01926 461501\r\n\r\nec@iaps.uk',
    'Bar Codes': '', 'Sending Status': 'Fine no problem',
    'Inv Booked Date': 'Thu 25 January 2024', 'Inv Send Out Date': 'Tue 4 June 2024',
    'Inv Due Back Date': 'Thu 13 June 2024', 'Number Wand Battery': '0',
    'Number Wand Charger': '0', 'Number Aerial Adapt': '0', 'Packed Date': '',
    'Packed Time': '', 'Unpacked Date': '', 'Unpacked Time': '',
    'Hire Sheet Printed': 'FALSE', 'ShipMe': 'FALSE', 'Missing Kit': '', 'Outbound ID': '',
    'PreShip Emailed': 'FALSE', 'To Customer': 'IAPS', 'Has document Log': '',
    'Involves Equipment': '', 'Inbound ID': ''
}, {
    'Name': 'MLS Contracts Ltd - 18/03/2024 ref 20358', 'Reference Number': '43129',
    'Booked Date': '20240112', 'Send Out Date': '20240318', 'Due Back Date': '20240327',
    'Status': 'Booked in', 'Actual Return Date': '',
    'Purpose': 'for event on 23/24 March\r\nset up 5 groups:\r\nChannel 1 – Alpha - Bravo\r\nChannel 2 – Charlie - Foxtrot\r\nChannel 3 – Queens Park Operations\r\nChannel 4 – Sports Presentation\r\nChannel 5 – Spare\r\n',
    'Closed': 'FALSE', 'Inv VHF Desc': '',
    'Delivery Address': 'c/o Canon Medical Arena\r\nWorksop Road\r\nAttercliffe\r\nSheffield',
    'Number Sgl Charger': '75', 'Inv UHF Price': '7.00', 'Delivery Postcode': 'S9 3TL',
    'Invoice': 'C:\\ProgramData\\Commence\\Commence\\8.0\\Data\\FILES\\a24591.docx',
    'Delivery Name': 'MLS Contracts Ltd', 'Payment Terms': 'Paid thanks',
    'Number VHF': '0', 'Number EM': '25', 'Number VHF 6-way': '0', 'Number ICOM PSU': '0',
    'Inv UHF Desc': 'Hire of Tesunho SIM TH388 walkie-talkie', 'Inv VHF Price': '',
    'Inv EM Desc': 'Hire of earpiece/microphone', 'Number Megaphone': '0',
    'Delivery Contact': 'Alison Bridge', 'Delivery Tel': '0114 257 3170',
    'Send / Collect': 'We send and pick up',
    'Send Method': 'Parcelforce/DB and we collect',
    'Hire Sheet Text': '\r\n* 75 x Tesunho SIM TH388 radios\r\n\r\n* 75 x single radio charger units\r\n\r\n* 25 x Earpiece/microphones (in re-usable bags)\r\n\r\n* 25 x extra radio battery packs\r\n\r\n* 1 x Laminated walkie-talkie instruction sheet',
    'Special Kit': '', 'Return Notes': '', 'Number UHF': '75', 'Number UHF 6-way': '0',
    'Number Parrot': '0', 'Number Headset': '0', 'Delivery Ref': '',
    'Number Batteries': '25', 'Number Cases': '0', 'Delivery Description': '',
    'Inv EM Price': '1.00', 'Inv Batt Desc': 'Hire of spare battery pack',
    'Inv Batt Price': '1.00', 'Inv Parrot Desc': '', 'Inv Parrot Price': '',
    'Inv Headset Desc': '', 'Inv Headset Price': '', 'Inv Case Desc': '',
    'Inv Case Price': '', 'Inv Send Desc': 'Send Date',
    'Inv Delivery Desc': 'Delivery & Collection',
    'Inv Return Desc': 'Cust. to advise when ready for collection',
    'Delivery Cost': '80.00', 'Purchase Order': '', 'Inv EM Qty': '25',
    'Inv Headset Qty': '', 'Inv Parrot Qty': '', 'Inv Batt Qty': '25', 'Inv Case Qty': '',
    'Inv UHF Qty': '75', 'Inv VHF Qty': '', 'Discount Percentage': '',
    'Discount Description': '', 'Instruc Walkies': 'TRUE', 'Number Megaphone Bat': '0',
    'Inv Mega Qty': '', 'Inv Mega Price': '', 'Inv Mega Desc': '',
    'Inv Charger Desc': 'Radio chargers included in price', 'Inv Meg Batt Desc': '',
    'Instruc Megaphone': 'FALSE', 'Instruc Icom': 'FALSE', 'Number Icom': '0',
    'Reprogrammed': 'FALSE', 'Inv Icom Desc': '', 'Inv Icom Qty': '', 'Inv Icom Price': '',
    'Megaphone charger': 'FALSE', 'Delivery Email': 'Alison.Bridge@MLSGB.CO',
    'Packed By': '', 'Unpacked by': '', 'Number EMC': '0', 'Number Headset Big': '0',
    'Inv EMC Desc': '', 'Inv EMC Price': '', 'Inv EMC Qty': '', 'Inv Bighead Desc': '',
    'Inv Bighead Price': '', 'Inv Bighead Qty': '', 'Number ICOM Car Lead': '0',
    'Weeks': '1', 'Boxes': '3', 'Inv Purchase Order': '', 'Number Magmount': '0',
    'Pickup Arranged': 'FALSE', 'Number Clipon Aerial': '0', 'Recurring Hire': 'FALSE',
    'Radio Type': 'Tesunho SIM TH388', 'Inv Wand Desc': '', 'Inv Wand Price': '',
    'Inv Wand Qty': '', 'Number Wand': '0', 'Number Repeater': '0',
    'DB label printed': 'FALSE',
    'All Address': 'Alison Bridge\r\nMLS Contracts Ltd\r\nc/o Canon Medical Arena\r\nWorksop Road\r\nAttercliffe\r\nSheffield\r\nS9 3TL\r\n\r\n0114 257 3170\r\n\r\nAlison.Bridge@MLSGB.CO',
    'Bar Codes': '', 'Sending Status': 'Fine no problem',
    'Inv Booked Date': 'Fri 12 January 2024', 'Inv Send Out Date': 'Mon 18 March 2024',
    'Inv Due Back Date': 'Wed 27 March 2024', 'Number Wand Battery': '0',
    'Number Wand Charger': '0', 'Number Aerial Adapt': '0', 'Packed Date': '',
    'Packed Time': '', 'Unpacked Date': '', 'Unpacked Time': '',
    'Hire Sheet Printed': 'FALSE', 'ShipMe': 'FALSE', 'Missing Kit': '', 'Outbound ID': '',
    'PreShip Emailed': 'FALSE', 'To Customer': 'MLS Contracts Ltd', 'Has document Log': '',
    'Involves Equipment': '', 'Inbound ID': ''
}, {
    'Name': 'Park Farm - 03/06/2024 ref 20371', 'Reference Number': '43171',
    'Booked Date': '20240123', 'Send Out Date': '20240603', 'Due Back Date': '20240612',
    'Status': 'Booked in', 'Actual Return Date': '', 'Purpose': 'for event Sun 9th June',
    'Closed': 'FALSE', 'Inv VHF Desc': '',
    'Delivery Address': 'Bath Soft Cheese LTD\r\nKelston\r\nBath',
    'Number Sgl Charger': '3', 'Inv UHF Price': '11.00', 'Delivery Postcode': 'BA1 9AQ',
    'Invoice': 'C:\\ProgramData\\Commence\\Commence\\8.0\\Data\\FILES\\a24626.docx',
    'Delivery Name': 'Park Farm', 'Payment Terms': 'To be paid before hire date',
    'Number VHF': '0', 'Number EM': '0', 'Number VHF 6-way': '0', 'Number ICOM PSU': '0',
    'Inv UHF Desc': 'Hire of Hytera Digital walkie-talkie', 'Inv VHF Price': '',
    'Inv EM Desc': '', 'Number Megaphone': '0', 'Delivery Contact': 'Camilla Wharton',
    'Delivery Tel': '01225 331601', 'Send / Collect': 'We send, cust return',
    'Send Method': 'Parcelforce / DB',
    'Hire Sheet Text': '\r\n* 15 x Hytera Digital radios\r\n\r\n* 2 x six-slot radio charger units\r\n\r\n* 3 x single radio charger units\r\n\r\n* 1 x leather cases with carry straps\r\n\r\n* 1 x remote speaker / microphones\r\n\r\n* 3 x extra radio battery packs\r\n\r\n* 1 x Laminated walkie-talkie instruction sheet',
    'Special Kit': '', 'Return Notes': '', 'Number UHF': '15', 'Number UHF 6-way': '2',
    'Number Parrot': '1', 'Number Headset': '0', 'Delivery Ref': '',
    'Number Batteries': '3', 'Number Cases': '1', 'Delivery Description': '',
    'Inv EM Price': '', 'Inv Batt Desc': 'Hire of spare battery pack',
    'Inv Batt Price': '1.00', 'Inv Parrot Desc': 'Hire of speaker / microphone',
    'Inv Parrot Price': '1.00', 'Inv Headset Desc': '', 'Inv Headset Price': '',
    'Inv Case Desc': 'Hire of leather case with neck strap', 'Inv Case Price': '1.00',
    'Inv Send Desc': 'Send Date', 'Inv Delivery Desc': 'Delivery',
    'Inv Return Desc': 'Customer to Return', 'Delivery Cost': '15.00',
    'Purchase Order': '', 'Inv EM Qty': '', 'Inv Headset Qty': '', 'Inv Parrot Qty': '1',
    'Inv Batt Qty': '3', 'Inv Case Qty': '1', 'Inv UHF Qty': '15', 'Inv VHF Qty': '',
    'Discount Percentage': '', 'Discount Description': '', 'Instruc Walkies': 'TRUE',
    'Number Megaphone Bat': '0', 'Inv Mega Qty': '', 'Inv Mega Price': '',
    'Inv Mega Desc': '', 'Inv Charger Desc': 'Radio chargers included in price',
    'Inv Meg Batt Desc': '', 'Instruc Megaphone': 'FALSE', 'Instruc Icom': 'FALSE',
    'Number Icom': '0', 'Reprogrammed': 'FALSE', 'Inv Icom Desc': '', 'Inv Icom Qty': '',
    'Inv Icom Price': '', 'Megaphone charger': 'FALSE',
    'Delivery Email': 'Camilla@parkfarm.co.uk', 'Packed By': '', 'Unpacked by': '',
    'Number EMC': '0', 'Number Headset Big': '0', 'Inv EMC Desc': '', 'Inv EMC Price': '',
    'Inv EMC Qty': '', 'Inv Bighead Desc': '', 'Inv Bighead Price': '',
    'Inv Bighead Qty': '', 'Number ICOM Car Lead': '0', 'Weeks': '1', 'Boxes': '1',
    'Inv Purchase Order': '', 'Number Magmount': '0', 'Pickup Arranged': 'FALSE',
    'Number Clipon Aerial': '0', 'Recurring Hire': 'FALSE', 'Radio Type': 'Hytera Digital',
    'Inv Wand Desc': '', 'Inv Wand Price': '', 'Inv Wand Qty': '', 'Number Wand': '0',
    'Number Repeater': '0', 'DB label printed': 'FALSE',
    'All Address': 'Camilla Wharton\r\nPark Farm\r\nBath Soft Cheese LTD\r\nKelston\r\nBath\r\nBA1 9AQ\r\n\r\n01225 331601\r\n\r\nCamilla@parkfarm.co.uk',
    'Bar Codes': '', 'Sending Status': 'Fine no problem',
    'Inv Booked Date': 'Tue 23 January 2024', 'Inv Send Out Date': 'Mon 3 June 2024',
    'Inv Due Back Date': 'Wed 12 June 2024', 'Number Wand Battery': '0',
    'Number Wand Charger': '0', 'Number Aerial Adapt': '0', 'Packed Date': '',
    'Packed Time': '', 'Unpacked Date': '', 'Unpacked Time': '',
    'Hire Sheet Printed': 'FALSE', 'ShipMe': 'FALSE', 'Missing Kit': '', 'Outbound ID': '',
    'PreShip Emailed': 'FALSE', 'To Customer': 'Park Farm', 'Has document Log': '',
    'Involves Equipment': '', 'Inbound ID': ''
}, {
    'Name': 'Pink Bear Events Ltd - 13/05/2024 ref 20226', 'Reference Number': '43183',
    'Booked Date': '20231002', 'Send Out Date': '20240513', 'Due Back Date': '20240725',
    'Status': 'Booked in', 'Actual Return Date': '', 'Purpose': 'for "TOTFEST" events',
    'Closed': 'FALSE', 'Inv VHF Desc': '',
    'Delivery Address': '2 Oak Tree Gardens\r\nKnebworth', 'Number Sgl Charger': '2',
    'Inv UHF Price': '21.00', 'Delivery Postcode': 'SG3 6EQ',
    'Invoice': 'C:\\ProgramData\\Commence\\Commence\\8.0\\Data\\FILES\\a24319.docx',
    'Delivery Name': 'Pink Bear Events', 'Payment Terms': 'To be paid before hire date',
    'Number VHF': '0', 'Number EM': '20', 'Number VHF 6-way': '0', 'Number ICOM PSU': '0',
    'Inv UHF Desc': 'Hire of Hytera Digital walkie-talkie', 'Inv VHF Price': '',
    'Inv EM Desc': 'Hire of earpiece/microphone', 'Number Megaphone': '0',
    'Delivery Contact': 'Madeline Griffiths', 'Delivery Tel': '07711 048237',
    'Send / Collect': 'We send and pick up',
    'Send Method': 'Parcelforce/DB and we collect',
    'Hire Sheet Text': '\r\n* 20 x Hytera Digital radios\r\n\r\n* 3 x six-slot radio charger units\r\n\r\n* 2 x single radio charger units\r\n\r\n* 20 x Earpiece/microphones (in re-usable bags)\r\n\r\n* 10 x leather cases with carry straps\r\n\r\n* 10 x extra radio battery packs\r\n\r\n* 1 x Laminated walkie-talkie instruction sheet',
    'Special Kit': '', 'Return Notes': '', 'Number UHF': '20', 'Number UHF 6-way': '3',
    'Number Parrot': '0', 'Number Headset': '0', 'Delivery Ref': '',
    'Number Batteries': '10', 'Number Cases': '10', 'Delivery Description': '',
    'Inv EM Price': '2.50', 'Inv Batt Desc': 'Hire of spare battery pack',
    'Inv Batt Price': '2.50', 'Inv Parrot Desc': '', 'Inv Parrot Price': '',
    'Inv Headset Desc': '', 'Inv Headset Price': '',
    'Inv Case Desc': 'Hire of leather case with neck strap', 'Inv Case Price': '2.50',
    'Inv Send Desc': 'Send Date', 'Inv Delivery Desc': 'Delivery & Collection',
    'Inv Return Desc': 'Cust. to advise when ready for collection',
    'Delivery Cost': '52.00', 'Purchase Order': '', 'Inv EM Qty': '20',
    'Inv Headset Qty': '', 'Inv Parrot Qty': '', 'Inv Batt Qty': '10',
    'Inv Case Qty': '10', 'Inv UHF Qty': '20', 'Inv VHF Qty': '',
    'Discount Percentage': '', 'Discount Description': '', 'Instruc Walkies': 'TRUE',
    'Number Megaphone Bat': '0', 'Inv Mega Qty': '', 'Inv Mega Price': '',
    'Inv Mega Desc': '', 'Inv Charger Desc': 'Radio chargers included in price',
    'Inv Meg Batt Desc': '', 'Instruc Megaphone': 'FALSE', 'Instruc Icom': 'FALSE',
    'Number Icom': '0', 'Reprogrammed': 'FALSE', 'Inv Icom Desc': '', 'Inv Icom Qty': '',
    'Inv Icom Price': '', 'Megaphone charger': 'FALSE',
    'Delivery Email': 'pinkbearevents@hotmail.com', 'Packed By': '', 'Unpacked by': '',
    'Number EMC': '0', 'Number Headset Big': '0', 'Inv EMC Desc': '', 'Inv EMC Price': '',
    'Inv EMC Qty': '', 'Inv Bighead Desc': '', 'Inv Bighead Price': '',
    'Inv Bighead Qty': '', 'Number ICOM Car Lead': '0', 'Weeks': '4', 'Boxes': '1',
    'Inv Purchase Order': '', 'Number Magmount': '0', 'Pickup Arranged': 'FALSE',
    'Number Clipon Aerial': '0', 'Recurring Hire': 'FALSE', 'Radio Type': 'Hytera Digital',
    'Inv Wand Desc': '', 'Inv Wand Price': '', 'Inv Wand Qty': '', 'Number Wand': '0',
    'Number Repeater': '0', 'DB label printed': 'FALSE',
    'All Address': 'Madeline Griffiths\r\nPink Bear Events\r\n2 Oak Tree Gardens\r\nKnebworth\r\nSG3 6EQ\r\n\r\n07711 048237\r\n\r\npinkbearevents@hotmail.com',
    'Bar Codes': '', 'Sending Status': 'Fine no problem',
    'Inv Booked Date': 'Mon 2 October 2023', 'Inv Send Out Date': 'Mon 13 May 2024',
    'Inv Due Back Date': 'Thu 25 July 2024', 'Number Wand Battery': '0',
    'Number Wand Charger': '0', 'Number Aerial Adapt': '0', 'Packed Date': '',
    'Packed Time': '', 'Unpacked Date': '', 'Unpacked Time': '',
    'Hire Sheet Printed': 'FALSE', 'ShipMe': 'FALSE', 'Missing Kit': '', 'Outbound ID': '',
    'PreShip Emailed': 'FALSE', 'To Customer': 'Pink Bear Events Ltd',
    'Has document Log': '', 'Involves Equipment': '', 'Inbound ID': ''
}, {
    'Name': 'Portsmouth Pride - 02/07/2024 ref 20359', 'Reference Number': '43191',
    'Booked Date': '20240112', 'Send Out Date': '20240702', 'Due Back Date': '20240711',
    'Status': 'Booked in', 'Actual Return Date': '', 'Purpose': 'for Portsmouth Pride',
    'Closed': 'FALSE', 'Inv VHF Desc': '',
    'Delivery Address': 'C/O 3 Brigham Close\r\nPortsmouth', 'Number Sgl Charger': '0',
    'Inv UHF Price': '7.00', 'Delivery Postcode': 'PO2 9EW',
    'Invoice': 'C:\\ProgramData\\Commence\\Commence\\8.0\\Data\\FILES\\a24595.docx',
    'Delivery Name': 'Portsmouth Pride', 'Payment Terms': 'To be paid before hire date',
    'Number VHF': '0', 'Number EM': '0', 'Number VHF 6-way': '0', 'Number ICOM PSU': '2',
    'Inv UHF Desc': 'Hire of Hytera Digital walkie-talkie', 'Inv VHF Price': '',
    'Inv EM Desc': '', 'Number Megaphone': '2', 'Delivery Contact': 'Dan Hickin',
    'Delivery Tel': '07722 415578', 'Send / Collect': 'We send and pick up',
    'Send Method': 'Parcelforce/DB and we collect',
    'Hire Sheet Text': '\r\n* 42 x Hytera Digital radios\r\n\r\n* 7 x six-slot radio charger units\r\n\r\n* 23 x Semi-covert earpiece/mics (in re-usable bags)\r\n\r\n* 16 x big aircraft-style headsets\r\n\r\n* 2 x vehicle/base radios\r\n\r\n* 2 x clip-on aerials\r\n\r\n* 2 x base radio mains power supplies\r\n\r\n* 2 Megaphones\r\n\r\n* 4 sets of 8 rechargeable batteries\r\n\r\n* 1 x Laminated walkie-talkie instruction sheet\r\n\r\n* 1 x Laminated mobile/base radio instruc sheet\r\n\r\n* 1 x Laminated megaphone instruction sheet\r\n\r\n* 3 x SIM card radios',
    'Special Kit': '* 3 x SIM card radios', 'Return Notes': '', 'Number UHF': '42',
    'Number UHF 6-way': '7', 'Number Parrot': '0', 'Number Headset': '0',
    'Delivery Ref': '', 'Number Batteries': '0', 'Number Cases': '0',
    'Delivery Description': '', 'Inv EM Price': '', 'Inv Batt Desc': '',
    'Inv Batt Price': '', 'Inv Parrot Desc': '', 'Inv Parrot Price': '',
    'Inv Headset Desc': '', 'Inv Headset Price': '', 'Inv Case Desc': '',
    'Inv Case Price': '', 'Inv Send Desc': 'Send Date',
    'Inv Delivery Desc': 'Delivery & Collection',
    'Inv Return Desc': 'Cust. to advise when ready for collection',
    'Delivery Cost': '72.00', 'Purchase Order': '', 'Inv EM Qty': '',
    'Inv Headset Qty': '', 'Inv Parrot Qty': '', 'Inv Batt Qty': '', 'Inv Case Qty': '',
    'Inv UHF Qty': '42', 'Inv VHF Qty': '', 'Discount Percentage': '25%',
    'Discount Description': 'Charity Discount', 'Instruc Walkies': 'TRUE',
    'Number Megaphone Bat': '4', 'Inv Mega Qty': '2', 'Inv Mega Price': '16.00',
    'Inv Mega Desc': 'Hire of megaphones',
    'Inv Charger Desc': 'Radio chargers included in price',
    'Inv Meg Batt Desc': '4 sets of 8 rechargeable batts included',
    'Instruc Megaphone': 'TRUE', 'Instruc Icom': 'TRUE', 'Number Icom': '2',
    'Reprogrammed': 'FALSE', 'Inv Icom Desc': 'Hire of vehicle/base radios',
    'Inv Icom Qty': '2', 'Inv Icom Price': '19.00', 'Megaphone charger': 'FALSE',
    'Delivery Email': 'dan.h@portsmouthpride.org.uk', 'Packed By': '', 'Unpacked by': '',
    'Number EMC': '23', 'Number Headset Big': '16',
    'Inv EMC Desc': 'Hire of semi-covert earpiece/mic', 'Inv EMC Price': '2.00',
    'Inv EMC Qty': '23', 'Inv Bighead Desc': 'Hire of aircraft-style big headset',
    'Inv Bighead Price': '5.00', 'Inv Bighead Qty': '16', 'Number ICOM Car Lead': '0',
    'Weeks': '1', 'Boxes': '3', 'Inv Purchase Order': '', 'Number Magmount': '0',
    'Pickup Arranged': 'FALSE', 'Number Clipon Aerial': '2', 'Recurring Hire': 'FALSE',
    'Radio Type': 'Hytera Digital', 'Inv Wand Desc': '', 'Inv Wand Price': '',
    'Inv Wand Qty': '', 'Number Wand': '0', 'Number Repeater': '0',
    'DB label printed': 'FALSE',
    'All Address': 'Dan Hickin\r\nPortsmouth Pride\r\nC/O 3 Brigham Close\r\nPortsmouth\r\nPO2 9EW\r\n\r\n07722 415578\r\n\r\ndan.h@portsmouthpride.org.uk',
    'Bar Codes': '', 'Sending Status': 'Fine no problem',
    'Inv Booked Date': 'Fri 12 January 2024', 'Inv Send Out Date': 'Tue 2 July 2024',
    'Inv Due Back Date': 'Thu 11 July 2024', 'Number Wand Battery': '0',
    'Number Wand Charger': '0', 'Number Aerial Adapt': '0', 'Packed Date': '',
    'Packed Time': '', 'Unpacked Date': '', 'Unpacked Time': '',
    'Hire Sheet Printed': 'FALSE', 'ShipMe': 'FALSE', 'Missing Kit': '', 'Outbound ID': '',
    'PreShip Emailed': 'FALSE', 'To Customer': 'Portsmouth Pride', 'Has document Log': '',
    'Involves Equipment': '', 'Inbound ID': ''
}, {
    'Name': 'RAC Saddle Club Office - 10/09/2024 ref 20395', 'Reference Number': '43202',
    'Booked Date': '20240205', 'Send Out Date': '20240910', 'Due Back Date': '20241003',
    'Status': 'Booked in', 'Actual Return Date': '',
    'Purpose': 'for event Sun 15 September and Sun 29 September', 'Closed': 'FALSE',
    'Inv VHF Desc': '',
    'Delivery Address': 'Allenby Barracks\r\nBovington\r\nWareham\r\nDorset',
    'Number Sgl Charger': '0', 'Inv UHF Price': '16.00', 'Delivery Postcode': 'BH20 6JA',
    'Invoice': 'C:\\ProgramData\\Commence\\Commence\\8.0\\Data\\FILES\\a24663.docx',
    'Delivery Name': 'RAC Saddle Club Office',
    'Payment Terms': 'To be paid before hire date', 'Number VHF': '0', 'Number EM': '0',
    'Number VHF 6-way': '0', 'Number ICOM PSU': '0',
    'Inv UHF Desc': 'Hire of Hytera Digital walkie-talkie', 'Inv VHF Price': '',
    'Inv EM Desc': '', 'Number Megaphone': '0', 'Delivery Contact': 'Kristal Bowdler',
    'Delivery Tel': '01929 403580', 'Send / Collect': 'We send and pick up',
    'Send Method': 'Parcelforce/DB and we collect',
    'Hire Sheet Text': '\r\n* 30 x Hytera Digital radios\r\n\r\n* 5 x six-slot radio charger units\r\n\r\n* 1 x Laminated walkie-talkie instruction sheet',
    'Special Kit': '', 'Return Notes': '', 'Number UHF': '30', 'Number UHF 6-way': '5',
    'Number Parrot': '0', 'Number Headset': '0', 'Delivery Ref': '',
    'Number Batteries': '0', 'Number Cases': '0', 'Delivery Description': '',
    'Inv EM Price': '', 'Inv Batt Desc': '', 'Inv Batt Price': '', 'Inv Parrot Desc': '',
    'Inv Parrot Price': '', 'Inv Headset Desc': '', 'Inv Headset Price': '',
    'Inv Case Desc': '', 'Inv Case Price': '', 'Inv Send Desc': 'Send Date',
    'Inv Delivery Desc': 'Delivery & Collection',
    'Inv Return Desc': 'Cust. to advise when ready for collection',
    'Delivery Cost': '60.00', 'Purchase Order': '', 'Inv EM Qty': '',
    'Inv Headset Qty': '', 'Inv Parrot Qty': '', 'Inv Batt Qty': '', 'Inv Case Qty': '',
    'Inv UHF Qty': '30', 'Inv VHF Qty': '', 'Discount Percentage': '25%',
    'Discount Description': 'Charity Discount', 'Instruc Walkies': 'TRUE',
    'Number Megaphone Bat': '0', 'Inv Mega Qty': '', 'Inv Mega Price': '',
    'Inv Mega Desc': '', 'Inv Charger Desc': 'Radio chargers included in price',
    'Inv Meg Batt Desc': '', 'Instruc Megaphone': 'FALSE', 'Instruc Icom': 'FALSE',
    'Number Icom': '0', 'Reprogrammed': 'FALSE', 'Inv Icom Desc': '', 'Inv Icom Qty': '',
    'Inv Icom Price': '', 'Megaphone charger': 'FALSE',
    'Delivery Email': 'kristalbowdler@gmail.com', 'Packed By': '', 'Unpacked by': '',
    'Number EMC': '0', 'Number Headset Big': '0', 'Inv EMC Desc': '', 'Inv EMC Price': '',
    'Inv EMC Qty': '', 'Inv Bighead Desc': '', 'Inv Bighead Price': '',
    'Inv Bighead Qty': '', 'Number ICOM Car Lead': '0', 'Weeks': '3', 'Boxes': '2',
    'Inv Purchase Order': '', 'Number Magmount': '0', 'Pickup Arranged': 'FALSE',
    'Number Clipon Aerial': '0', 'Recurring Hire': 'FALSE', 'Radio Type': 'Hytera Digital',
    'Inv Wand Desc': '', 'Inv Wand Price': '', 'Inv Wand Qty': '', 'Number Wand': '0',
    'Number Repeater': '0', 'DB label printed': 'FALSE',
    'All Address': 'Kristal Bowdler\r\nRAC Saddle Club Office\r\nAllenby Barracks\r\nBovington\r\nWareham\r\nDorset\r\nBH20 6JA\r\n\r\n01929 403580\r\n\r\nkristalbowdler@gmail.com',
    'Bar Codes': '', 'Sending Status': 'Fine no problem',
    'Inv Booked Date': 'Mon 5 February 2024', 'Inv Send Out Date': 'Tue 10 September 2024',
    'Inv Due Back Date': 'Thu 3 October 2024', 'Number Wand Battery': '0',
    'Number Wand Charger': '0', 'Number Aerial Adapt': '0', 'Packed Date': '',
    'Packed Time': '', 'Unpacked Date': '', 'Unpacked Time': '',
    'Hire Sheet Printed': 'FALSE', 'ShipMe': 'FALSE', 'Missing Kit': '', 'Outbound ID': '',
    'PreShip Emailed': 'FALSE', 'To Customer': 'RAC Saddle Club Office',
    'Has document Log': '', 'Involves Equipment': '', 'Inbound ID': ''
}, {
    'Name': 'RAC Saddle Club Office - 30/04/2024 ref 20394', 'Reference Number': '43203',
    'Booked Date': '20240205', 'Send Out Date': '20240430', 'Due Back Date': '20240508',
    'Status': 'Booked in', 'Actual Return Date': '', 'Purpose': 'for event Sunday 5 May',
    'Closed': 'FALSE', 'Inv VHF Desc': '',
    'Delivery Address': 'Allenby Barracks\r\nBovington\r\nWareham\r\nDorset',
    'Number Sgl Charger': '0', 'Inv UHF Price': '7.00', 'Delivery Postcode': 'BH20 6JA',
    'Invoice': 'C:\\ProgramData\\Commence\\Commence\\8.0\\Data\\FILES\\a24662.docx',
    'Delivery Name': 'RAC Saddle Club Office',
    'Payment Terms': 'To be paid before hire date', 'Number VHF': '0', 'Number EM': '0',
    'Number VHF 6-way': '0', 'Number ICOM PSU': '0',
    'Inv UHF Desc': 'Hire of Hytera Digital walkie-talkie', 'Inv VHF Price': '',
    'Inv EM Desc': '', 'Number Megaphone': '0', 'Delivery Contact': 'Kristal Bowdler',
    'Delivery Tel': '07793 744068', 'Send / Collect': 'We send and pick up',
    'Send Method': 'Parcelforce/DB and we collect',
    'Hire Sheet Text': '\r\n* 30 x Hytera Digital radios\r\n\r\n* 5 x six-slot radio charger units\r\n\r\n* 1 x Laminated walkie-talkie instruction sheet',
    'Special Kit': '', 'Return Notes': '', 'Number UHF': '30', 'Number UHF 6-way': '5',
    'Number Parrot': '0', 'Number Headset': '0', 'Delivery Ref': '',
    'Number Batteries': '0', 'Number Cases': '0', 'Delivery Description': '',
    'Inv EM Price': '', 'Inv Batt Desc': '', 'Inv Batt Price': '', 'Inv Parrot Desc': '',
    'Inv Parrot Price': '', 'Inv Headset Desc': '', 'Inv Headset Price': '',
    'Inv Case Desc': '', 'Inv Case Price': '', 'Inv Send Desc': 'Send Date',
    'Inv Delivery Desc': 'Delivery & Collection',
    'Inv Return Desc': 'Cust. to advise when ready for collection',
    'Delivery Cost': '60.00', 'Purchase Order': '', 'Inv EM Qty': '',
    'Inv Headset Qty': '', 'Inv Parrot Qty': '', 'Inv Batt Qty': '', 'Inv Case Qty': '',
    'Inv UHF Qty': '30', 'Inv VHF Qty': '', 'Discount Percentage': '25%',
    'Discount Description': 'Charity Discount', 'Instruc Walkies': 'TRUE',
    'Number Megaphone Bat': '0', 'Inv Mega Qty': '', 'Inv Mega Price': '',
    'Inv Mega Desc': '', 'Inv Charger Desc': 'Radio chargers included in price',
    'Inv Meg Batt Desc': '', 'Instruc Megaphone': 'FALSE', 'Instruc Icom': 'FALSE',
    'Number Icom': '0', 'Reprogrammed': 'FALSE', 'Inv Icom Desc': '', 'Inv Icom Qty': '',
    'Inv Icom Price': '', 'Megaphone charger': 'FALSE',
    'Delivery Email': 'kristalbowdler@gmail.com', 'Packed By': '', 'Unpacked by': '',
    'Number EMC': '0', 'Number Headset Big': '0', 'Inv EMC Desc': '', 'Inv EMC Price': '',
    'Inv EMC Qty': '', 'Inv Bighead Desc': '', 'Inv Bighead Price': '',
    'Inv Bighead Qty': '', 'Number ICOM Car Lead': '0', 'Weeks': '1', 'Boxes': '2',
    'Inv Purchase Order': '', 'Number Magmount': '0', 'Pickup Arranged': 'FALSE',
    'Number Clipon Aerial': '0', 'Recurring Hire': 'FALSE', 'Radio Type': 'Hytera Digital',
    'Inv Wand Desc': '', 'Inv Wand Price': '', 'Inv Wand Qty': '', 'Number Wand': '0',
    'Number Repeater': '0', 'DB label printed': 'FALSE',
    'All Address': 'Kristal Bowdler\r\nRAC Saddle Club Office\r\nAllenby Barracks\r\nBovington\r\nWareham\r\nDorset\r\nBH20 6JA\r\n\r\n07793 744068\r\n\r\nkristalbowdler@gmail.com',
    'Bar Codes': '', 'Sending Status': 'Fine no problem',
    'Inv Booked Date': 'Mon 5 February 2024', 'Inv Send Out Date': 'Tue 30 April 2024',
    'Inv Due Back Date': 'Wed 8 May 2024', 'Number Wand Battery': '0',
    'Number Wand Charger': '0', 'Number Aerial Adapt': '0', 'Packed Date': '',
    'Packed Time': '', 'Unpacked Date': '', 'Unpacked Time': '',
    'Hire Sheet Printed': 'FALSE', 'ShipMe': 'FALSE', 'Missing Kit': '', 'Outbound ID': '',
    'PreShip Emailed': 'FALSE', 'To Customer': 'RAC Saddle Club Office',
    'Has document Log': '', 'Involves Equipment': '', 'Inbound ID': ''
}, {
    'Name': 'Ruth Donaldson - 20/02/2024 ref 20407', 'Reference Number': '43234',
    'Booked Date': '20240209', 'Send Out Date': '20240220', 'Due Back Date': '20240228',
    'Status': 'Booked in', 'Actual Return Date': '', 'Purpose': 'for protest Sat 24/02',
    'Closed': 'FALSE', 'Inv VHF Desc': '',
    'Delivery Address': '2 St Georges Road\r\nLONDON', 'Number Sgl Charger': '0',
    'Inv UHF Price': '', 'Delivery Postcode': 'N13 4AS',
    'Invoice': 'C:\\ProgramData\\Commence\\Commence\\8.0\\Data\\FILES\\a24682.docx',
    'Delivery Name': 'Ruth Donaldson', 'Payment Terms': 'Due for payment please',
    'Number VHF': '0', 'Number EM': '0', 'Number VHF 6-way': '0', 'Number ICOM PSU': '0',
    'Inv UHF Desc': '', 'Inv VHF Price': '', 'Inv EM Desc': '', 'Number Megaphone': '2',
    'Delivery Contact': 'Ruth Donaldson', 'Delivery Tel': '07980 305332',
    'Send / Collect': 'We send, cust return', 'Send Method': 'Parcelforce / DB',
    'Hire Sheet Text': '\r\n\r\n* 2 Megaphones\r\n\r\n* 4 sets of 8 rechargeable batteries\r\n\r\n* 1 x Laminated megaphone instruction sheet',
    'Special Kit': '', 'Return Notes': '', 'Number UHF': '0', 'Number UHF 6-way': '0',
    'Number Parrot': '0', 'Number Headset': '0', 'Delivery Ref': '',
    'Number Batteries': '0', 'Number Cases': '0', 'Delivery Description': '',
    'Inv EM Price': '', 'Inv Batt Desc': '', 'Inv Batt Price': '', 'Inv Parrot Desc': '',
    'Inv Parrot Price': '', 'Inv Headset Desc': '', 'Inv Headset Price': '',
    'Inv Case Desc': '', 'Inv Case Price': '', 'Inv Send Desc': 'Send Date',
    'Inv Delivery Desc': 'Delivery', 'Inv Return Desc': 'Customer to Return',
    'Delivery Cost': '15.00', 'Purchase Order': '', 'Inv EM Qty': '',
    'Inv Headset Qty': '', 'Inv Parrot Qty': '', 'Inv Batt Qty': '', 'Inv Case Qty': '',
    'Inv UHF Qty': '', 'Inv VHF Qty': '', 'Discount Percentage': '',
    'Discount Description': '', 'Instruc Walkies': 'FALSE', 'Number Megaphone Bat': '4',
    'Inv Mega Qty': '2', 'Inv Mega Price': '16.00', 'Inv Mega Desc': 'Hire of megaphones',
    'Inv Charger Desc': '', 'Inv Meg Batt Desc': '4 sets of 8 rechargeable batts included',
    'Instruc Megaphone': 'TRUE', 'Instruc Icom': 'FALSE', 'Number Icom': '0',
    'Reprogrammed': 'FALSE', 'Inv Icom Desc': '', 'Inv Icom Qty': '', 'Inv Icom Price': '',
    'Megaphone charger': 'FALSE', 'Delivery Email': 'ruthie_md@hotmail.com',
    'Packed By': '', 'Unpacked by': '', 'Number EMC': '0', 'Number Headset Big': '0',
    'Inv EMC Desc': '', 'Inv EMC Price': '', 'Inv EMC Qty': '', 'Inv Bighead Desc': '',
    'Inv Bighead Price': '', 'Inv Bighead Qty': '', 'Number ICOM Car Lead': '0',
    'Weeks': '1', 'Boxes': '1', 'Inv Purchase Order': '', 'Number Magmount': '0',
    'Pickup Arranged': 'FALSE', 'Number Clipon Aerial': '0', 'Recurring Hire': 'FALSE',
    'Radio Type': 'not selected', 'Inv Wand Desc': '', 'Inv Wand Price': '',
    'Inv Wand Qty': '', 'Number Wand': '0', 'Number Repeater': '0',
    'DB label printed': 'FALSE',
    'All Address': 'Ruth Donaldson\r\nRuth Donaldson\r\n2 St Georges Road\r\nLONDON\r\nN13 4AS\r\n\r\n07980 305332\r\n\r\nruthie_md@hotmail.com',
    'Bar Codes': '', 'Sending Status': 'Fine no problem',
    'Inv Booked Date': 'Fri 9 February 2024', 'Inv Send Out Date': 'Tue 20 February 2024',
    'Inv Due Back Date': 'Wed 28 February 2024', 'Number Wand Battery': '0',
    'Number Wand Charger': '0', 'Number Aerial Adapt': '0', 'Packed Date': '',
    'Packed Time': '', 'Unpacked Date': '', 'Unpacked Time': '',
    'Hire Sheet Printed': 'FALSE', 'ShipMe': 'FALSE', 'Missing Kit': '', 'Outbound ID': '',
    'PreShip Emailed': 'FALSE', 'To Customer': 'Ruth Donaldson', 'Has document Log': '',
    'Involves Equipment': '', 'Inbound ID': ''
}, {
    'Name': 'St Philip Howard Catholic S - 27/02/2024 ref 31835',
    'Reference Number': '43265', 'Booked Date': '20240110', 'Send Out Date': '20240227',
    'Due Back Date': '20240311', 'Status': 'Booked in', 'Actual Return Date': '',
    'Purpose': '', 'Closed': 'FALSE', 'Inv VHF Desc': '',
    'Delivery Address': 'Elm Grove South\r\nBarnham\r\nWest Sussex',
    'Number Sgl Charger': '0', 'Inv UHF Price': '11.00', 'Delivery Postcode': 'PO22 0EN',
    'Invoice': 'C:\\ProgramData\\Commence\\Commence\\8.0\\Data\\FILES\\A24589.docx',
    'Delivery Name': 'St Philip Howard Catholic School',
    'Payment Terms': 'To be paid before hire date', 'Number VHF': '0', 'Number EM': '0',
    'Number VHF 6-way': '0', 'Number ICOM PSU': '0',
    'Inv UHF Desc': 'Hire of Kirisun UHF walkie-talkie', 'Inv VHF Price': '',
    'Inv EM Desc': '', 'Number Megaphone': '0', 'Delivery Contact': 'Matt Bonner',
    'Delivery Tel': '01243 552055', 'Send / Collect': 'We send and pick up',
    'Send Method': 'Parcelforce/DB and we collect',
    'Hire Sheet Text': '\r\n* 10 x Kirisun UHF radios\r\n\r\n* 2 x six-slot radio charger units\r\n\r\n* 10 x headsets with boom mics\r\n\r\n* 5 x extra radio battery packs\r\n\r\n* 1 x Laminated walkie-talkie instruction sheet',
    'Special Kit': '', 'Return Notes': '', 'Number UHF': '10', 'Number UHF 6-way': '2',
    'Number Parrot': '0', 'Number Headset': '10', 'Delivery Ref': '',
    'Number Batteries': '5', 'Number Cases': '0', 'Delivery Description': '',
    'Inv EM Price': '', 'Inv Batt Desc': 'Hire of spare battery pack',
    'Inv Batt Price': '1.00', 'Inv Parrot Desc': '', 'Inv Parrot Price': '',
    'Inv Headset Desc': 'Hire of headset', 'Inv Headset Price': '2.00',
    'Inv Case Desc': '', 'Inv Case Price': '', 'Inv Send Desc': 'Send Date',
    'Inv Delivery Desc': 'Delivery & Collection',
    'Inv Return Desc': 'Cust. to advise when ready for collection',
    'Delivery Cost': '35.00', 'Purchase Order': '', 'Inv EM Qty': '',
    'Inv Headset Qty': '10', 'Inv Parrot Qty': '', 'Inv Batt Qty': '5', 'Inv Case Qty': '',
    'Inv UHF Qty': '10', 'Inv VHF Qty': '', 'Discount Percentage': '',
    'Discount Description': '', 'Instruc Walkies': 'TRUE', 'Number Megaphone Bat': '0',
    'Inv Mega Qty': '', 'Inv Mega Price': '', 'Inv Mega Desc': '',
    'Inv Charger Desc': 'Radio chargers included in price', 'Inv Meg Batt Desc': '',
    'Instruc Megaphone': 'FALSE', 'Instruc Icom': 'FALSE', 'Number Icom': '0',
    'Reprogrammed': 'FALSE', 'Inv Icom Desc': '', 'Inv Icom Qty': '', 'Inv Icom Price': '',
    'Megaphone charger': 'FALSE', 'Delivery Email': 'mbonner@sphcs.co.uk', 'Packed By': '',
    'Unpacked by': '', 'Number EMC': '0', 'Number Headset Big': '0', 'Inv EMC Desc': '',
    'Inv EMC Price': '', 'Inv EMC Qty': '', 'Inv Bighead Desc': '',
    'Inv Bighead Price': '', 'Inv Bighead Qty': '', 'Number ICOM Car Lead': '0',
    'Weeks': '1', 'Boxes': '1', 'Inv Purchase Order': '', 'Number Magmount': '0',
    'Pickup Arranged': 'FALSE', 'Number Clipon Aerial': '0', 'Recurring Hire': 'FALSE',
    'Radio Type': 'Kirisun UHF', 'Inv Wand Desc': '', 'Inv Wand Price': '',
    'Inv Wand Qty': '', 'Number Wand': '0', 'Number Repeater': '0',
    'DB label printed': 'FALSE',
    'All Address': 'Matt Bonner\r\nSt Philip Howard Catholic School\r\nElm Grove South\r\nBarnham\r\nWest Sussex\r\nPO22 0EN\r\n\r\n01243 552055\r\n\r\nmbonner@sphcs.co.uk',
    'Bar Codes': '', 'Sending Status': 'Fine no problem',
    'Inv Booked Date': 'Wed 10 January 2024', 'Inv Send Out Date': 'Tue 27 February 2024',
    'Inv Due Back Date': 'Mon 11 March 2024', 'Number Wand Battery': '0',
    'Number Wand Charger': '0', 'Number Aerial Adapt': '0', 'Packed Date': '',
    'Packed Time': '', 'Unpacked Date': '', 'Unpacked Time': '',
    'Hire Sheet Printed': 'FALSE', 'ShipMe': 'FALSE', 'Missing Kit': '', 'Outbound ID': '',
    'PreShip Emailed': 'FALSE', 'To Customer': 'St Philip Howard Catholic School',
    'Has document Log': '', 'Involves Equipment': '', 'Inbound ID': ''
}, {
    'Name': 'Surrey Young Farmers / Cowp - 06/05/2024 ref 20300',
    'Reference Number': '43272', 'Booked Date': '20231115', 'Send Out Date': '20240506',
    'Due Back Date': '20240515', 'Status': 'Booked in', 'Actual Return Date': '',
    'Purpose': 'for "Cow Pie" show Sun 12th May 2024', 'Closed': 'FALSE',
    'Inv VHF Desc': '',
    'Delivery Address': "Neil Fuller\r\nSurrey Young Farmers / Cowpie Show\r\nJob's Farm\r\nNew House Lane\r\nRedhill",
    'Number Sgl Charger': '1', 'Inv UHF Price': '7.00', 'Delivery Postcode': 'RH1 5RE',
    'Invoice': 'C:\\ProgramData\\Commence\\Commence\\8.0\\Data\\FILES\\a24462.docx',
    'Delivery Name': "Job's Farm", 'Payment Terms': 'To be paid before hire date',
    'Number VHF': '0', 'Number EM': '30', 'Number VHF 6-way': '0', 'Number ICOM PSU': '0',
    'Inv UHF Desc': 'Hire of Hytera Digital walkie-talkie', 'Inv VHF Price': '',
    'Inv EM Desc': 'Hire of earpiece/microphone', 'Number Megaphone': '3',
    'Delivery Contact': 'Neil Fuller', 'Delivery Tel': '07860 241817',
    'Send / Collect': 'We send and pick up',
    'Send Method': 'Parcelforce/DB and we collect',
    'Hire Sheet Text': '\r\n* 55 x Hytera Digital radios\r\n\r\n* 9 x six-slot radio charger units\r\n\r\n* 1 x single radio charger units\r\n\r\n* 30 x Earpiece/microphones (in re-usable bags)\r\n\r\n* 55 x leather cases with carry straps\r\n\r\n* 10 x extra radio battery packs\r\n\r\n* 3 Megaphones\r\n\r\n* 6 sets of 8 rechargeable batteries\r\n\r\n* 1 x megaphone battery charger unit\r\n\r\n* 1 x Laminated walkie-talkie instruction sheet',
    'Special Kit': '', 'Return Notes': '', 'Number UHF': '55', 'Number UHF 6-way': '9',
    'Number Parrot': '0', 'Number Headset': '0', 'Delivery Ref': '',
    'Number Batteries': '10', 'Number Cases': '55', 'Delivery Description': '',
    'Inv EM Price': '1.00', 'Inv Batt Desc': 'Hire of spare battery pack',
    'Inv Batt Price': '1.00', 'Inv Parrot Desc': '', 'Inv Parrot Price': '',
    'Inv Headset Desc': '', 'Inv Headset Price': '',
    'Inv Case Desc': 'Hire of leather case with neck strap', 'Inv Case Price': '1.00',
    'Inv Send Desc': 'Send Date', 'Inv Delivery Desc': 'Delivery & Collection',
    'Inv Return Desc': 'Cust. to advise when ready for collection',
    'Delivery Cost': '60.00', 'Purchase Order': '', 'Inv EM Qty': '30',
    'Inv Headset Qty': '', 'Inv Parrot Qty': '', 'Inv Batt Qty': '10',
    'Inv Case Qty': '55', 'Inv UHF Qty': '55', 'Inv VHF Qty': '',
    'Discount Percentage': '', 'Discount Description': '', 'Instruc Walkies': 'TRUE',
    'Number Megaphone Bat': '6', 'Inv Mega Qty': '3', 'Inv Mega Price': '16.00',
    'Inv Mega Desc': 'Hire of megaphones',
    'Inv Charger Desc': 'Radio chargers included in price',
    'Inv Meg Batt Desc': '6 sets of 8 rechargeable batts included',
    'Instruc Megaphone': 'FALSE', 'Instruc Icom': 'FALSE', 'Number Icom': '0',
    'Reprogrammed': 'FALSE', 'Inv Icom Desc': '', 'Inv Icom Qty': '', 'Inv Icom Price': '',
    'Megaphone charger': 'TRUE', 'Delivery Email': 'njffarming@hotmail.co.uk',
    'Packed By': '', 'Unpacked by': '', 'Number EMC': '0', 'Number Headset Big': '0',
    'Inv EMC Desc': '', 'Inv EMC Price': '', 'Inv EMC Qty': '', 'Inv Bighead Desc': '',
    'Inv Bighead Price': '', 'Inv Bighead Qty': '', 'Number ICOM Car Lead': '0',
    'Weeks': '1', 'Boxes': '3', 'Inv Purchase Order': '', 'Number Magmount': '0',
    'Pickup Arranged': 'FALSE', 'Number Clipon Aerial': '0', 'Recurring Hire': 'FALSE',
    'Radio Type': 'Hytera Digital', 'Inv Wand Desc': '', 'Inv Wand Price': '',
    'Inv Wand Qty': '', 'Number Wand': '0', 'Number Repeater': '0',
    'DB label printed': 'FALSE',
    'All Address': "Neil Fuller\r\nJob's Farm\r\nNeil Fuller\r\nSurrey Young Farmers / Cowpie Show\r\nJob's Farm\r\nNew House Lane\r\nRedhill\r\nRH1 5RE\r\n\r\n07860 241817\r\n\r\nnjffarming@hotmail.co.uk",
    'Bar Codes': '', 'Sending Status': 'Fine no problem',
    'Inv Booked Date': 'Wed 15 November 2023', 'Inv Send Out Date': 'Mon 6 May 2024',
    'Inv Due Back Date': 'Wed 15 May 2024', 'Number Wand Battery': '0',
    'Number Wand Charger': '0', 'Number Aerial Adapt': '0', 'Packed Date': '',
    'Packed Time': '', 'Unpacked Date': '', 'Unpacked Time': '',
    'Hire Sheet Printed': 'FALSE', 'ShipMe': 'FALSE', 'Missing Kit': '', 'Outbound ID': '',
    'PreShip Emailed': 'FALSE', 'To Customer': 'Surrey Young Farmers / Cowpie Show',
    'Has document Log': '', 'Involves Equipment': '', 'Inbound ID': ''
}, {
    'Name': 'Trampoline League - 10/09/2023 ref 20384', 'Reference Number': '43312',
    'Booked Date': '20240129', 'Send Out Date': '20240910', 'Due Back Date': '20240919',
    'Status': 'Booked in', 'Actual Return Date': '', 'Purpose': 'for event 13/9 -16/09',
    'Closed': 'FALSE', 'Inv VHF Desc': '',
    'Delivery Address': '98 Kenpas Highway \r\nGreen Lane \r\nCoventry',
    'Number Sgl Charger': '2', 'Inv UHF Price': '11.00', 'Delivery Postcode': 'CV3 6BQ',
    'Invoice': 'C:\\ProgramData\\Commence\\Commence\\8.0\\Data\\FILES\\a24669.docx',
    'Delivery Name': 'Trampoline League', 'Payment Terms': 'To be paid before hire date',
    'Number VHF': '0', 'Number EM': '14', 'Number VHF 6-way': '0', 'Number ICOM PSU': '0',
    'Inv UHF Desc': 'Hire of Kirisun UHF walkie-talkie', 'Inv VHF Price': '',
    'Inv EM Desc': 'Hire of earpiece/microphone', 'Number Megaphone': '0',
    'Delivery Contact': 'Jayne Armitage', 'Delivery Tel': '07845 419917',
    'Send / Collect': 'We send and pick up',
    'Send Method': 'Parcelforce/DB and we collect',
    'Hire Sheet Text': '\r\n* 14 x Kirisun UHF radios\r\n\r\n* 2 x six-slot radio charger units\r\n\r\n* 2 x single radio charger units\r\n\r\n* 14 x Earpiece/microphones (in re-usable bags)\r\n\r\n* 7 x extra radio battery packs\r\n\r\n* 1 x Laminated walkie-talkie instruction sheet',
    'Special Kit': '', 'Return Notes': '', 'Number UHF': '14', 'Number UHF 6-way': '2',
    'Number Parrot': '0', 'Number Headset': '0', 'Delivery Ref': '',
    'Number Batteries': '7', 'Number Cases': '0', 'Delivery Description': '',
    'Inv EM Price': '1.00', 'Inv Batt Desc': 'Hire of spare battery pack',
    'Inv Batt Price': '1.00', 'Inv Parrot Desc': '', 'Inv Parrot Price': '',
    'Inv Headset Desc': '', 'Inv Headset Price': '', 'Inv Case Desc': '',
    'Inv Case Price': '', 'Inv Send Desc': 'Send Date',
    'Inv Delivery Desc': 'Delivery & Collection',
    'Inv Return Desc': 'Cust. to advise when ready for collection',
    'Delivery Cost': '35.00', 'Purchase Order': '', 'Inv EM Qty': '14',
    'Inv Headset Qty': '', 'Inv Parrot Qty': '', 'Inv Batt Qty': '7', 'Inv Case Qty': '',
    'Inv UHF Qty': '14', 'Inv VHF Qty': '', 'Discount Percentage': '15%',
    'Discount Description': 'Agreed discount', 'Instruc Walkies': 'TRUE',
    'Number Megaphone Bat': '0', 'Inv Mega Qty': '', 'Inv Mega Price': '',
    'Inv Mega Desc': '', 'Inv Charger Desc': 'Radio chargers included in price',
    'Inv Meg Batt Desc': '', 'Instruc Megaphone': 'FALSE', 'Instruc Icom': 'FALSE',
    'Number Icom': '0', 'Reprogrammed': 'FALSE', 'Inv Icom Desc': '', 'Inv Icom Qty': '',
    'Inv Icom Price': '', 'Megaphone charger': 'FALSE',
    'Delivery Email': 'jayne2911@gmail.com', 'Packed By': '', 'Unpacked by': '',
    'Number EMC': '0', 'Number Headset Big': '0', 'Inv EMC Desc': '', 'Inv EMC Price': '',
    'Inv EMC Qty': '', 'Inv Bighead Desc': '', 'Inv Bighead Price': '',
    'Inv Bighead Qty': '', 'Number ICOM Car Lead': '0', 'Weeks': '1', 'Boxes': '1',
    'Inv Purchase Order': '', 'Number Magmount': '0', 'Pickup Arranged': 'FALSE',
    'Number Clipon Aerial': '0', 'Recurring Hire': 'FALSE', 'Radio Type': 'Kirisun UHF',
    'Inv Wand Desc': '', 'Inv Wand Price': '', 'Inv Wand Qty': '', 'Number Wand': '0',
    'Number Repeater': '0', 'DB label printed': 'FALSE',
    'All Address': 'Jayne Armitage\r\nTrampoline League\r\n98 Kenpas Highway \r\nGreen Lane \r\nCoventry\r\nCV3 6BQ\r\n\r\n07845 419917\r\n\r\njayne2911@gmail.com',
    'Bar Codes': '', 'Sending Status': 'Fine no problem',
    'Inv Booked Date': 'Mon 29 January 2024', 'Inv Send Out Date': 'Tue 10 September 2024',
    'Inv Due Back Date': 'Thu 19 September 2024', 'Number Wand Battery': '0',
    'Number Wand Charger': '0', 'Number Aerial Adapt': '0', 'Packed Date': '',
    'Packed Time': '', 'Unpacked Date': '', 'Unpacked Time': '',
    'Hire Sheet Printed': 'FALSE', 'ShipMe': 'FALSE', 'Missing Kit': '', 'Outbound ID': '',
    'PreShip Emailed': 'FALSE', 'To Customer': 'Trampoline League', 'Has document Log': '',
    'Involves Equipment': '', 'Inbound ID': ''
}, {
    'Name': 'Trampoline League - 19/03/2024 ref 20382', 'Reference Number': '43313',
    'Booked Date': '20240129', 'Send Out Date': '20240319', 'Due Back Date': '20240327',
    'Status': 'Booked in', 'Actual Return Date': '', 'Purpose': 'for event 21-25 march',
    'Closed': 'FALSE', 'Inv VHF Desc': '',
    'Delivery Address': '98 Kenpas Highway \r\nGreen Lane \r\nCoventry',
    'Number Sgl Charger': '2', 'Inv UHF Price': '11.00', 'Delivery Postcode': 'CV3 6BQ',
    'Invoice': 'C:\\ProgramData\\Commence\\Commence\\8.0\\Data\\FILES\\a24644.docx',
    'Delivery Name': 'Trampoline League', 'Payment Terms': 'To be paid before hire date',
    'Number VHF': '0', 'Number EM': '14', 'Number VHF 6-way': '0', 'Number ICOM PSU': '0',
    'Inv UHF Desc': 'Hire of Kirisun UHF walkie-talkie', 'Inv VHF Price': '',
    'Inv EM Desc': 'Hire of earpiece/microphone', 'Number Megaphone': '0',
    'Delivery Contact': 'Jayne Armitage', 'Delivery Tel': '07845 419917',
    'Send / Collect': 'We send and pick up',
    'Send Method': 'Parcelforce/DB and we collect',
    'Hire Sheet Text': '\r\n* 14 x Kirisun UHF radios\r\n\r\n* 2 x six-slot radio charger units\r\n\r\n* 2 x single radio charger units\r\n\r\n* 14 x Earpiece/microphones (in re-usable bags)\r\n\r\n* 7 x extra radio battery packs\r\n\r\n* 1 x Laminated walkie-talkie instruction sheet',
    'Special Kit': '', 'Return Notes': '', 'Number UHF': '14', 'Number UHF 6-way': '2',
    'Number Parrot': '0', 'Number Headset': '0', 'Delivery Ref': '',
    'Number Batteries': '7', 'Number Cases': '0', 'Delivery Description': '',
    'Inv EM Price': '1.00', 'Inv Batt Desc': 'Hire of spare battery pack',
    'Inv Batt Price': '1.00', 'Inv Parrot Desc': '', 'Inv Parrot Price': '',
    'Inv Headset Desc': '', 'Inv Headset Price': '', 'Inv Case Desc': '',
    'Inv Case Price': '', 'Inv Send Desc': 'Send Date',
    'Inv Delivery Desc': 'Delivery & Collection',
    'Inv Return Desc': 'Cust. to advise when ready for collection',
    'Delivery Cost': '35.00', 'Purchase Order': '', 'Inv EM Qty': '14',
    'Inv Headset Qty': '', 'Inv Parrot Qty': '', 'Inv Batt Qty': '7', 'Inv Case Qty': '',
    'Inv UHF Qty': '14', 'Inv VHF Qty': '', 'Discount Percentage': '15%',
    'Discount Description': 'Agreed discount', 'Instruc Walkies': 'TRUE',
    'Number Megaphone Bat': '0', 'Inv Mega Qty': '', 'Inv Mega Price': '',
    'Inv Mega Desc': '', 'Inv Charger Desc': 'Radio chargers included in price',
    'Inv Meg Batt Desc': '', 'Instruc Megaphone': 'FALSE', 'Instruc Icom': 'FALSE',
    'Number Icom': '0', 'Reprogrammed': 'FALSE', 'Inv Icom Desc': '', 'Inv Icom Qty': '',
    'Inv Icom Price': '', 'Megaphone charger': 'FALSE',
    'Delivery Email': 'jayne2911@gmail.com', 'Packed By': '', 'Unpacked by': '',
    'Number EMC': '0', 'Number Headset Big': '0', 'Inv EMC Desc': '', 'Inv EMC Price': '',
    'Inv EMC Qty': '', 'Inv Bighead Desc': '', 'Inv Bighead Price': '',
    'Inv Bighead Qty': '', 'Number ICOM Car Lead': '0', 'Weeks': '1', 'Boxes': '1',
    'Inv Purchase Order': '', 'Number Magmount': '0', 'Pickup Arranged': 'FALSE',
    'Number Clipon Aerial': '0', 'Recurring Hire': 'FALSE', 'Radio Type': 'Kirisun UHF',
    'Inv Wand Desc': '', 'Inv Wand Price': '', 'Inv Wand Qty': '', 'Number Wand': '0',
    'Number Repeater': '0', 'DB label printed': 'FALSE',
    'All Address': 'Jayne Armitage\r\nTrampoline League\r\n98 Kenpas Highway \r\nGreen Lane \r\nCoventry\r\nCV3 6BQ\r\n\r\n07845 419917\r\n\r\njayne2911@gmail.com',
    'Bar Codes': '', 'Sending Status': 'Fine no problem',
    'Inv Booked Date': 'Mon 29 January 2024', 'Inv Send Out Date': 'Tue 19 March 2024',
    'Inv Due Back Date': 'Wed 27 March 2024', 'Number Wand Battery': '0',
    'Number Wand Charger': '0', 'Number Aerial Adapt': '0', 'Packed Date': '',
    'Packed Time': '', 'Unpacked Date': '', 'Unpacked Time': '',
    'Hire Sheet Printed': 'FALSE', 'ShipMe': 'FALSE', 'Missing Kit': '', 'Outbound ID': '',
    'PreShip Emailed': 'FALSE', 'To Customer': 'Trampoline League', 'Has document Log': '',
    'Involves Equipment': '', 'Inbound ID': ''
}, {
    'Name': 'Trampoline League - 28/05/2024 ref 20383', 'Reference Number': '43314',
    'Booked Date': '20240129', 'Send Out Date': '20240528', 'Due Back Date': '20240605',
    'Status': 'Booked in', 'Actual Return Date': '', 'Purpose': 'for event 29/05-2/6',
    'Closed': 'FALSE', 'Inv VHF Desc': '',
    'Delivery Address': '98 Kenpas Highway \r\nGreen Lane \r\nCoventry',
    'Number Sgl Charger': '2', 'Inv UHF Price': '11.00', 'Delivery Postcode': 'CV3 6BQ',
    'Invoice': 'C:\\ProgramData\\Commence\\Commence\\8.0\\Data\\FILES\\a24668.docx',
    'Delivery Name': 'Trampoline League', 'Payment Terms': 'To be paid before hire date',
    'Number VHF': '0', 'Number EM': '14', 'Number VHF 6-way': '0', 'Number ICOM PSU': '0',
    'Inv UHF Desc': 'Hire of Kirisun UHF walkie-talkie', 'Inv VHF Price': '',
    'Inv EM Desc': 'Hire of earpiece/microphone', 'Number Megaphone': '0',
    'Delivery Contact': 'Jayne Armitage', 'Delivery Tel': '07845 419917',
    'Send / Collect': 'We send and pick up',
    'Send Method': 'Parcelforce/DB and we collect',
    'Hire Sheet Text': '\r\n* 14 x Kirisun UHF radios\r\n\r\n* 2 x six-slot radio charger units\r\n\r\n* 2 x single radio charger units\r\n\r\n* 14 x Earpiece/microphones (in re-usable bags)\r\n\r\n* 7 x extra radio battery packs\r\n\r\n* 1 x Laminated walkie-talkie instruction sheet',
    'Special Kit': '', 'Return Notes': '', 'Number UHF': '14', 'Number UHF 6-way': '2',
    'Number Parrot': '0', 'Number Headset': '0', 'Delivery Ref': '',
    'Number Batteries': '7', 'Number Cases': '0', 'Delivery Description': '',
    'Inv EM Price': '1.00', 'Inv Batt Desc': 'Hire of spare battery pack',
    'Inv Batt Price': '1.00', 'Inv Parrot Desc': '', 'Inv Parrot Price': '',
    'Inv Headset Desc': '', 'Inv Headset Price': '', 'Inv Case Desc': '',
    'Inv Case Price': '', 'Inv Send Desc': 'Send Date',
    'Inv Delivery Desc': 'Delivery & Collection',
    'Inv Return Desc': 'Cust. to advise when ready for collection',
    'Delivery Cost': '35.00', 'Purchase Order': '', 'Inv EM Qty': '14',
    'Inv Headset Qty': '', 'Inv Parrot Qty': '', 'Inv Batt Qty': '7', 'Inv Case Qty': '',
    'Inv UHF Qty': '14', 'Inv VHF Qty': '', 'Discount Percentage': '15%',
    'Discount Description': 'Agreed discount', 'Instruc Walkies': 'TRUE',
    'Number Megaphone Bat': '0', 'Inv Mega Qty': '', 'Inv Mega Price': '',
    'Inv Mega Desc': '', 'Inv Charger Desc': 'Radio chargers included in price',
    'Inv Meg Batt Desc': '', 'Instruc Megaphone': 'FALSE', 'Instruc Icom': 'FALSE',
    'Number Icom': '0', 'Reprogrammed': 'FALSE', 'Inv Icom Desc': '', 'Inv Icom Qty': '',
    'Inv Icom Price': '', 'Megaphone charger': 'FALSE',
    'Delivery Email': 'jayne2911@gmail.com', 'Packed By': '', 'Unpacked by': '',
    'Number EMC': '0', 'Number Headset Big': '0', 'Inv EMC Desc': '', 'Inv EMC Price': '',
    'Inv EMC Qty': '', 'Inv Bighead Desc': '', 'Inv Bighead Price': '',
    'Inv Bighead Qty': '', 'Number ICOM Car Lead': '0', 'Weeks': '1', 'Boxes': '1',
    'Inv Purchase Order': '', 'Number Magmount': '0', 'Pickup Arranged': 'FALSE',
    'Number Clipon Aerial': '0', 'Recurring Hire': 'FALSE', 'Radio Type': 'Kirisun UHF',
    'Inv Wand Desc': '', 'Inv Wand Price': '', 'Inv Wand Qty': '', 'Number Wand': '0',
    'Number Repeater': '0', 'DB label printed': 'FALSE',
    'All Address': 'Jayne Armitage\r\nTrampoline League\r\n98 Kenpas Highway \r\nGreen Lane \r\nCoventry\r\nCV3 6BQ\r\n\r\n07845 419917\r\n\r\njayne2911@gmail.com',
    'Bar Codes': '', 'Sending Status': 'Fine no problem',
    'Inv Booked Date': 'Mon 29 January 2024', 'Inv Send Out Date': 'Tue 28 May 2024',
    'Inv Due Back Date': 'Wed 5 June 2024', 'Number Wand Battery': '0',
    'Number Wand Charger': '0', 'Number Aerial Adapt': '0', 'Packed Date': '',
    'Packed Time': '', 'Unpacked Date': '', 'Unpacked Time': '',
    'Hire Sheet Printed': 'FALSE', 'ShipMe': 'FALSE', 'Missing Kit': '', 'Outbound ID': '',
    'PreShip Emailed': 'FALSE', 'To Customer': 'Trampoline League', 'Has document Log': '',
    'Involves Equipment': '', 'Inbound ID': ''
}, {
    'Name': 'Truly Blessed Promotions - 27/02/2024 ref 20362', 'Reference Number': '43318',
    'Booked Date': '20240116', 'Send Out Date': '20240227', 'Due Back Date': '20240305',
    'Status': 'Booked in', 'Actual Return Date': '',
    'Purpose': 'for event on Sat 2nd March in Leeds', 'Closed': 'FALSE',
    'Inv VHF Desc': '',
    'Delivery Address': '*** COLLECTED FROM AMHERST OFFICE ***\r\n70 Kingsgate Road\r\nLondon',
    'Number Sgl Charger': '0', 'Inv UHF Price': '7.00', 'Delivery Postcode': 'NW6 4TE',
    'Invoice': 'C:\\ProgramData\\Commence\\Commence\\8.0\\Data\\FILES\\a24606.docx',
    'Delivery Name': 'Truly Blessed Promotions',
    'Payment Terms': 'To be paid before hire date', 'Number VHF': '0', 'Number EM': '15',
    'Number VHF 6-way': '0', 'Number ICOM PSU': '0',
    'Inv UHF Desc': 'Hire of Hytera Digital walkie-talkie', 'Inv VHF Price': '',
    'Inv EM Desc': 'Hire of earpiece/microphone', 'Number Megaphone': '0',
    'Delivery Contact': 'Raza Saba', 'Delivery Tel': '07707 504616',
    'Send / Collect': 'Cust. collect/return', 'Send Method': 'he collects',
    'Hire Sheet Text': '\r\n* 35 x Hytera Digital radios\r\n\r\n* 6 x six-slot radio charger units\r\n\r\n* 15 x Earpiece/microphones (in re-usable bags)\r\n\r\n* 20 x Semi-covert earpiece/mics (in re-usable bags)\r\n\r\n* 10 x extra radio battery packs\r\n\r\n* 1 x Laminated walkie-talkie instruction sheet',
    'Special Kit': '', 'Return Notes': '', 'Number UHF': '35', 'Number UHF 6-way': '6',
    'Number Parrot': '0', 'Number Headset': '0', 'Delivery Ref': '',
    'Number Batteries': '10', 'Number Cases': '0', 'Delivery Description': '',
    'Inv EM Price': '1.00', 'Inv Batt Desc': 'Hire of spare battery pack',
    'Inv Batt Price': '1.00', 'Inv Parrot Desc': '', 'Inv Parrot Price': '',
    'Inv Headset Desc': '', 'Inv Headset Price': '', 'Inv Case Desc': '',
    'Inv Case Price': '', 'Inv Send Desc': 'Collect Date', 'Inv Delivery Desc': '',
    'Inv Return Desc': 'Customer to Return', 'Delivery Cost': '', 'Purchase Order': '',
    'Inv EM Qty': '15', 'Inv Headset Qty': '', 'Inv Parrot Qty': '', 'Inv Batt Qty': '10',
    'Inv Case Qty': '', 'Inv UHF Qty': '35', 'Inv VHF Qty': '', 'Discount Percentage': '',
    'Discount Description': '', 'Instruc Walkies': 'TRUE', 'Number Megaphone Bat': '0',
    'Inv Mega Qty': '', 'Inv Mega Price': '', 'Inv Mega Desc': '',
    'Inv Charger Desc': 'Radio chargers included in price', 'Inv Meg Batt Desc': '',
    'Instruc Megaphone': 'FALSE', 'Instruc Icom': 'FALSE', 'Number Icom': '0',
    'Reprogrammed': 'FALSE', 'Inv Icom Desc': '', 'Inv Icom Qty': '', 'Inv Icom Price': '',
    'Megaphone charger': 'FALSE', 'Delivery Email': 'sabar1987@hotmail.co.uk',
    'Packed By': '', 'Unpacked by': '', 'Number EMC': '20', 'Number Headset Big': '0',
    'Inv EMC Desc': 'Hire of semi-covert earpiece/mic', 'Inv EMC Price': '2.00',
    'Inv EMC Qty': '20', 'Inv Bighead Desc': '', 'Inv Bighead Price': '',
    'Inv Bighead Qty': '', 'Number ICOM Car Lead': '0', 'Weeks': '1', 'Boxes': '1',
    'Inv Purchase Order': '', 'Number Magmount': '0', 'Pickup Arranged': 'FALSE',
    'Number Clipon Aerial': '0', 'Recurring Hire': 'FALSE', 'Radio Type': 'Hytera Digital',
    'Inv Wand Desc': '', 'Inv Wand Price': '', 'Inv Wand Qty': '', 'Number Wand': '0',
    'Number Repeater': '0', 'DB label printed': 'FALSE',
    'All Address': 'Raza Saba\r\nTruly Blessed Promotions\r\n*** COLLECTED FROM AMHERST OFFICE ***\r\n70 Kingsgate Road\r\nLondon\r\nNW6 4TE\r\n\r\n07707 504616\r\n\r\nsabar1987@hotmail.co.uk',
    'Bar Codes': '', 'Sending Status': 'Fine no problem',
    'Inv Booked Date': 'Tue 16 January 2024', 'Inv Send Out Date': 'Tue 27 February 2024',
    'Inv Due Back Date': 'Tue 5 March 2024', 'Number Wand Battery': '0',
    'Number Wand Charger': '0', 'Number Aerial Adapt': '0', 'Packed Date': '',
    'Packed Time': '', 'Unpacked Date': '', 'Unpacked Time': '',
    'Hire Sheet Printed': 'FALSE', 'ShipMe': 'FALSE', 'Missing Kit': '', 'Outbound ID': '',
    'PreShip Emailed': 'FALSE', 'To Customer': 'Truly Blessed Promotions',
    'Has document Log': '', 'Involves Equipment': '', 'Inbound ID': ''
}, {
    'Name': 'Twisted Automotive - 09/04/2024 ref 20366', 'Reference Number': '43322',
    'Booked Date': '20240118', 'Send Out Date': '20240409', 'Due Back Date': '20240422',
    'Status': 'Booked in', 'Actual Return Date': '', 'Purpose': '', 'Closed': 'FALSE',
    'Inv VHF Desc': '',
    'Delivery Address': 'Sussex Court\r\nThirsk Ind. Park\r\nYork Road\r\nThirsk\r\nNorth Yorkshire',
    'Number Sgl Charger': '0', 'Inv UHF Price': '11.00', 'Delivery Postcode': 'YO7 3TA',
    'Invoice': 'C:\\ProgramData\\Commence\\Commence\\8.0\\Data\\FILES\\a24616.docx',
    'Delivery Name': 'Twisted Automotive', 'Payment Terms': 'To be paid before hire date',
    'Number VHF': '0', 'Number EM': '0', 'Number VHF 6-way': '0', 'Number ICOM PSU': '0',
    'Inv UHF Desc': 'Hire of Hytera Digital walkie-talkie', 'Inv VHF Price': '',
    'Inv EM Desc': '', 'Number Megaphone': '0', 'Delivery Contact': 'Katie Mckenzie',
    'Delivery Tel': '07548 706851', 'Send / Collect': 'We send and pick up',
    'Send Method': 'Parcelforce/DB and we collect',
    'Hire Sheet Text': '\r\n* 18 x Hytera Digital radios\r\n\r\n* 3 x six-slot radio charger units\r\n\r\n* 1 x Laminated walkie-talkie instruction sheet',
    'Special Kit': '', 'Return Notes': '', 'Number UHF': '18', 'Number UHF 6-way': '3',
    'Number Parrot': '0', 'Number Headset': '0', 'Delivery Ref': '',
    'Number Batteries': '0', 'Number Cases': '0', 'Delivery Description': '',
    'Inv EM Price': '', 'Inv Batt Desc': '', 'Inv Batt Price': '', 'Inv Parrot Desc': '',
    'Inv Parrot Price': '', 'Inv Headset Desc': '', 'Inv Headset Price': '',
    'Inv Case Desc': '', 'Inv Case Price': '', 'Inv Send Desc': 'Send Date',
    'Inv Delivery Desc': 'Delivery & Collection',
    'Inv Return Desc': 'Cust. to advise when ready for collection',
    'Delivery Cost': '35.00', 'Purchase Order': '', 'Inv EM Qty': '',
    'Inv Headset Qty': '', 'Inv Parrot Qty': '', 'Inv Batt Qty': '', 'Inv Case Qty': '',
    'Inv UHF Qty': '18', 'Inv VHF Qty': '', 'Discount Percentage': '',
    'Discount Description': '', 'Instruc Walkies': 'TRUE', 'Number Megaphone Bat': '0',
    'Inv Mega Qty': '', 'Inv Mega Price': '', 'Inv Mega Desc': '',
    'Inv Charger Desc': 'Radio chargers included in price', 'Inv Meg Batt Desc': '',
    'Instruc Megaphone': 'FALSE', 'Instruc Icom': 'FALSE', 'Number Icom': '0',
    'Reprogrammed': 'FALSE', 'Inv Icom Desc': '', 'Inv Icom Qty': '', 'Inv Icom Price': '',
    'Megaphone charger': 'FALSE', 'Delivery Email': 'katie@twistedautomotive.com',
    'Packed By': '', 'Unpacked by': '', 'Number EMC': '0', 'Number Headset Big': '0',
    'Inv EMC Desc': '', 'Inv EMC Price': '', 'Inv EMC Qty': '', 'Inv Bighead Desc': '',
    'Inv Bighead Price': '', 'Inv Bighead Qty': '', 'Number ICOM Car Lead': '0',
    'Weeks': '1', 'Boxes': '1', 'Inv Purchase Order': '', 'Number Magmount': '0',
    'Pickup Arranged': 'FALSE', 'Number Clipon Aerial': '0', 'Recurring Hire': 'FALSE',
    'Radio Type': 'Hytera Digital', 'Inv Wand Desc': '', 'Inv Wand Price': '',
    'Inv Wand Qty': '', 'Number Wand': '0', 'Number Repeater': '0',
    'DB label printed': 'FALSE',
    'All Address': 'Katie Mckenzie\r\nTwisted Automotive\r\nSussex Court\r\nThirsk Ind. Park\r\nYork Road\r\nThirsk\r\nNorth Yorkshire\r\nYO7 3TA\r\n\r\n07548 706851\r\n\r\nkatie@twistedautomotive.com',
    'Bar Codes': '', 'Sending Status': 'Fine no problem',
    'Inv Booked Date': 'Thu 18 January 2024', 'Inv Send Out Date': 'Tue 9 April 2024',
    'Inv Due Back Date': 'Mon 22 April 2024', 'Number Wand Battery': '0',
    'Number Wand Charger': '0', 'Number Aerial Adapt': '0', 'Packed Date': '',
    'Packed Time': '', 'Unpacked Date': '', 'Unpacked Time': '',
    'Hire Sheet Printed': 'FALSE', 'ShipMe': 'FALSE', 'Missing Kit': '', 'Outbound ID': '',
    'PreShip Emailed': 'FALSE', 'To Customer': 'Twisted Automotive',
    'Has document Log': '', 'Involves Equipment': '', 'Inbound ID': ''
}, {
    'Name': 'Verve Festival Ltd - 16/09/2024 ref 20294', 'Reference Number': '43342',
    'Booked Date': '20231109', 'Send Out Date': '20240916', 'Due Back Date': '20240925',
    'Status': 'Booked in', 'Actual Return Date': '',
    'Purpose': 'for festival 20-22 September 2024', 'Closed': 'FALSE', 'Inv VHF Desc': '',
    'Delivery Address': 'Wistaria House\r\nThe Cross\r\nEbbesbourne Wake',
    'Number Sgl Charger': '3', 'Inv UHF Price': '11.00', 'Delivery Postcode': 'SP5 5JF',
    'Invoice': 'C:\\ProgramData\\Commence\\Commence\\8.0\\Data\\FILES\\a24442.docx',
    'Delivery Name': 'Verve Festival Ltd', 'Payment Terms': 'To be paid before hire date',
    'Number VHF': '0', 'Number EM': '15', 'Number VHF 6-way': '0', 'Number ICOM PSU': '0',
    'Inv UHF Desc': 'Hire of Hytera Digital walkie-talkie', 'Inv VHF Price': '',
    'Inv EM Desc': 'Hire of earpiece/microphone', 'Number Megaphone': '1',
    'Delivery Contact': 'Charlotte Cummings', 'Delivery Tel': '07946 055445',
    'Send / Collect': 'We send and pick up',
    'Send Method': 'Parcelforce/DB and we collect',
    'Hire Sheet Text': '\r\n* 15 x Hytera Digital radios\r\n\r\n* 2 x six-slot radio charger units\r\n\r\n* 3 x single radio charger units\r\n\r\n* 15 x Earpiece/microphones (in re-usable bags)\r\n\r\n* 8 x extra radio battery packs\r\n\r\n* 1 Megaphone\r\n\r\n* 2 sets of 8 rechargeable batteries\r\n\r\n* 1 x megaphone battery charger unit\r\n\r\n* 1 x Laminated walkie-talkie instruction sheet\r\n\r\n* 1 x Laminated megaphone instruction sheet',
    'Special Kit': '', 'Return Notes': '', 'Number UHF': '15', 'Number UHF 6-way': '2',
    'Number Parrot': '0', 'Number Headset': '0', 'Delivery Ref': '',
    'Number Batteries': '8', 'Number Cases': '0', 'Delivery Description': '',
    'Inv EM Price': '1.00', 'Inv Batt Desc': 'Hire of spare battery pack',
    'Inv Batt Price': '1.00', 'Inv Parrot Desc': '', 'Inv Parrot Price': '',
    'Inv Headset Desc': '', 'Inv Headset Price': '', 'Inv Case Desc': '',
    'Inv Case Price': '', 'Inv Send Desc': 'Send Date',
    'Inv Delivery Desc': 'Delivery & Collection',
    'Inv Return Desc': 'Cust. to advise when ready for collection',
    'Delivery Cost': '54.00', 'Purchase Order': '', 'Inv EM Qty': '15',
    'Inv Headset Qty': '', 'Inv Parrot Qty': '', 'Inv Batt Qty': '8', 'Inv Case Qty': '',
    'Inv UHF Qty': '15', 'Inv VHF Qty': '', 'Discount Percentage': '',
    'Discount Description': '', 'Instruc Walkies': 'TRUE', 'Number Megaphone Bat': '2',
    'Inv Mega Qty': '1', 'Inv Mega Price': '16.00', 'Inv Mega Desc': 'Hire of megaphone',
    'Inv Charger Desc': 'Radio chargers included in price',
    'Inv Meg Batt Desc': '2 sets of 8 rechargeable batts included',
    'Instruc Megaphone': 'TRUE', 'Instruc Icom': 'FALSE', 'Number Icom': '0',
    'Reprogrammed': 'FALSE', 'Inv Icom Desc': '', 'Inv Icom Qty': '', 'Inv Icom Price': '',
    'Megaphone charger': 'TRUE', 'Delivery Email': 'charlotte@feeltheverve.com',
    'Packed By': '', 'Unpacked by': '', 'Number EMC': '0', 'Number Headset Big': '0',
    'Inv EMC Desc': '', 'Inv EMC Price': '', 'Inv EMC Qty': '', 'Inv Bighead Desc': '',
    'Inv Bighead Price': '', 'Inv Bighead Qty': '', 'Number ICOM Car Lead': '0',
    'Weeks': '1', 'Boxes': '2', 'Inv Purchase Order': '', 'Number Magmount': '0',
    'Pickup Arranged': 'FALSE', 'Number Clipon Aerial': '0', 'Recurring Hire': 'FALSE',
    'Radio Type': 'Hytera Digital', 'Inv Wand Desc': '', 'Inv Wand Price': '',
    'Inv Wand Qty': '', 'Number Wand': '0', 'Number Repeater': '0',
    'DB label printed': 'FALSE',
    'All Address': 'Charlotte Cummings\r\nVerve Festival Ltd\r\nWistaria House\r\nThe Cross\r\nEbbesbourne Wake\r\nSP5 5JF\r\n\r\n07946 055445\r\n\r\ncharlotte@feeltheverve.com',
    'Bar Codes': '', 'Sending Status': 'Fine no problem',
    'Inv Booked Date': 'Thu 9 November 2023', 'Inv Send Out Date': 'Mon 16 September 2024',
    'Inv Due Back Date': 'Wed 25 September 2024', 'Number Wand Battery': '0',
    'Number Wand Charger': '0', 'Number Aerial Adapt': '0', 'Packed Date': '',
    'Packed Time': '', 'Unpacked Date': '', 'Unpacked Time': '',
    'Hire Sheet Printed': 'FALSE', 'ShipMe': 'FALSE', 'Missing Kit': '', 'Outbound ID': '',
    'PreShip Emailed': 'FALSE', 'To Customer': 'Verve Festival Ltd',
    'Has document Log': '', 'Involves Equipment': '', 'Inbound ID': ''
}, {
    'Name': 'Well Hung and Tender - 19/06/2024 ref 31826', 'Reference Number': '43357',
    'Booked Date': '20240104', 'Send Out Date': '20240619', 'Due Back Date': '20240628',
    'Status': 'Booked in', 'Actual Return Date': '', 'Purpose': '', 'Closed': 'FALSE',
    'Inv VHF Desc': '', 'Delivery Address': 'Castlehills Farm\r\nBerwick upon Tweed',
    'Number Sgl Charger': '3', 'Inv UHF Price': '11.00', 'Delivery Postcode': 'TD15 1PB',
    'Invoice': 'C:\\ProgramData\\Commence\\Commence\\8.0\\Data\\FILES\\A24571.docx',
    'Delivery Name': 'Well Hung and Tender', 'Payment Terms': 'Paid thanks',
    'Number VHF': '0', 'Number EM': '8', 'Number VHF 6-way': '0', 'Number ICOM PSU': '0',
    'Inv UHF Desc': 'Hire of Kirisun UHF walkie-talkie', 'Inv VHF Price': '',
    'Inv EM Desc': 'Hire of earpiece/microphone', 'Number Megaphone': '0',
    'Delivery Contact': 'Sarah Manson', 'Delivery Tel': '01289 303070',
    'Send / Collect': 'We send and pick up',
    'Send Method': 'Parcelforce/DB and we collect',
    'Hire Sheet Text': '\r\n* 15 x Kirisun UHF radios\r\n\r\n* 2 x six-slot radio charger units\r\n\r\n* 3 x single radio charger units\r\n\r\n* 8 x Earpiece/microphones (in re-usable bags)\r\n\r\n* 8 x extra radio battery packs\r\n\r\n* 1 x Laminated walkie-talkie instruction sheet',
    'Special Kit': '', 'Return Notes': '', 'Number UHF': '15', 'Number UHF 6-way': '2',
    'Number Parrot': '0', 'Number Headset': '0', 'Delivery Ref': '',
    'Number Batteries': '8', 'Number Cases': '0', 'Delivery Description': '',
    'Inv EM Price': '1.00', 'Inv Batt Desc': 'Hire of spare battery pack',
    'Inv Batt Price': '1.00', 'Inv Parrot Desc': '', 'Inv Parrot Price': '',
    'Inv Headset Desc': '', 'Inv Headset Price': '', 'Inv Case Desc': '',
    'Inv Case Price': '', 'Inv Send Desc': 'Send Date',
    'Inv Delivery Desc': 'Delivery & Collection',
    'Inv Return Desc': 'Cust. to advise when ready for collection',
    'Delivery Cost': '35.00', 'Purchase Order': '', 'Inv EM Qty': '8',
    'Inv Headset Qty': '', 'Inv Parrot Qty': '', 'Inv Batt Qty': '8', 'Inv Case Qty': '',
    'Inv UHF Qty': '15', 'Inv VHF Qty': '', 'Discount Percentage': '',
    'Discount Description': '', 'Instruc Walkies': 'TRUE', 'Number Megaphone Bat': '0',
    'Inv Mega Qty': '', 'Inv Mega Price': '', 'Inv Mega Desc': '',
    'Inv Charger Desc': 'Radio chargers included in price', 'Inv Meg Batt Desc': '',
    'Instruc Megaphone': 'FALSE', 'Instruc Icom': 'FALSE', 'Number Icom': '0',
    'Reprogrammed': 'FALSE', 'Inv Icom Desc': '', 'Inv Icom Qty': '', 'Inv Icom Price': '',
    'Megaphone charger': 'FALSE', 'Delivery Email': 'info@wellhungandtender.com',
    'Packed By': '', 'Unpacked by': '', 'Number EMC': '0', 'Number Headset Big': '0',
    'Inv EMC Desc': '', 'Inv EMC Price': '', 'Inv EMC Qty': '', 'Inv Bighead Desc': '',
    'Inv Bighead Price': '', 'Inv Bighead Qty': '', 'Number ICOM Car Lead': '0',
    'Weeks': '1', 'Boxes': '1', 'Inv Purchase Order': '', 'Number Magmount': '0',
    'Pickup Arranged': 'FALSE', 'Number Clipon Aerial': '0', 'Recurring Hire': 'FALSE',
    'Radio Type': 'Kirisun UHF', 'Inv Wand Desc': '', 'Inv Wand Price': '',
    'Inv Wand Qty': '', 'Number Wand': '0', 'Number Repeater': '0',
    'DB label printed': 'FALSE',
    'All Address': 'Sarah Manson\r\nWell Hung and Tender\r\nCastlehills Farm\r\nBerwick upon Tweed\r\nTD15 1PB\r\n\r\n01289 303070\r\n\r\ninfo@wellhungandtender.com',
    'Bar Codes': '', 'Sending Status': 'Fine no problem',
    'Inv Booked Date': 'Thu 4 January 2024', 'Inv Send Out Date': 'Wed 19 June 2024',
    'Inv Due Back Date': 'Fri 28 June 2024', 'Number Wand Battery': '0',
    'Number Wand Charger': '0', 'Number Aerial Adapt': '0', 'Packed Date': '',
    'Packed Time': '', 'Unpacked Date': '', 'Unpacked Time': '',
    'Hire Sheet Printed': 'FALSE', 'ShipMe': 'FALSE', 'Missing Kit': '', 'Outbound ID': '',
    'PreShip Emailed': 'FALSE', 'To Customer': 'Well Hung and Tender',
    'Has document Log': '', 'Involves Equipment': '', 'Inbound ID': ''
}, {
    'Name': 'Welsh 2 day Enduro - 21/06/2024 ref 20388', 'Reference Number': '43358',
    'Booked Date': '20240131', 'Send Out Date': '20240621', 'Due Back Date': '20240701',
    'Status': 'Booked in', 'Actual Return Date': '',
    'Purpose': 'for 2 day Enduro event \r\n Wednesday 26th - Friday 28th June',
    'Closed': 'FALSE', 'Inv VHF Desc': '',
    'Delivery Address': '1 Moat Cottage \r\nBeguildy \r\nKnighton \r\nShropshire',
    'Number Sgl Charger': '40', 'Inv UHF Price': '7.00', 'Delivery Postcode': 'LD7 1YU',
    'Invoice': 'C:\\ProgramData\\Commence\\Commence\\8.0\\Data\\FILES\\a24651.docx',
    'Delivery Name': 'Welsh 2 day Enduro', 'Payment Terms': 'To be paid before hire date',
    'Number VHF': '0', 'Number EM': '0', 'Number VHF 6-way': '0', 'Number ICOM PSU': '0',
    'Inv UHF Desc': 'Hire of Tesunho SIM TH388 walkie-talkie', 'Inv VHF Price': '',
    'Inv EM Desc': '', 'Number Megaphone': '0', 'Delivery Contact': 'Caitlin Mockler',
    'Delivery Tel': '07788 500295?', 'Send / Collect': 'We send and pick up',
    'Send Method': 'Parcelforce/DB and we collect',
    'Hire Sheet Text': '\r\n* 40 x Tesunho SIM TH388 radios\r\n\r\n* 40 x single radio charger units\r\n\r\n* 1 x Laminated walkie-talkie instruction sheet',
    'Special Kit': '', 'Return Notes': '', 'Number UHF': '40', 'Number UHF 6-way': '0',
    'Number Parrot': '0', 'Number Headset': '0', 'Delivery Ref': '',
    'Number Batteries': '0', 'Number Cases': '0', 'Delivery Description': '',
    'Inv EM Price': '', 'Inv Batt Desc': '', 'Inv Batt Price': '', 'Inv Parrot Desc': '',
    'Inv Parrot Price': '', 'Inv Headset Desc': '', 'Inv Headset Price': '',
    'Inv Case Desc': '', 'Inv Case Price': '', 'Inv Send Desc': 'Send Date',
    'Inv Delivery Desc': 'Delivery & Collection',
    'Inv Return Desc': 'Cust. to advise when ready for collection',
    'Delivery Cost': '64.00', 'Purchase Order': '', 'Inv EM Qty': '',
    'Inv Headset Qty': '', 'Inv Parrot Qty': '', 'Inv Batt Qty': '', 'Inv Case Qty': '',
    'Inv UHF Qty': '40', 'Inv VHF Qty': '', 'Discount Percentage': '',
    'Discount Description': '', 'Instruc Walkies': 'TRUE', 'Number Megaphone Bat': '0',
    'Inv Mega Qty': '', 'Inv Mega Price': '', 'Inv Mega Desc': '',
    'Inv Charger Desc': 'Radio chargers included in price', 'Inv Meg Batt Desc': '',
    'Instruc Megaphone': 'FALSE', 'Instruc Icom': 'FALSE', 'Number Icom': '0',
    'Reprogrammed': 'FALSE', 'Inv Icom Desc': '', 'Inv Icom Qty': '', 'Inv Icom Price': '',
    'Megaphone charger': 'FALSE', 'Delivery Email': 'caitlinmockler@hotmail.com',
    'Packed By': '', 'Unpacked by': '', 'Number EMC': '0', 'Number Headset Big': '0',
    'Inv EMC Desc': '', 'Inv EMC Price': '', 'Inv EMC Qty': '', 'Inv Bighead Desc': '',
    'Inv Bighead Price': '', 'Inv Bighead Qty': '', 'Number ICOM Car Lead': '0',
    'Weeks': '1', 'Boxes': '2', 'Inv Purchase Order': '', 'Number Magmount': '0',
    'Pickup Arranged': 'FALSE', 'Number Clipon Aerial': '0', 'Recurring Hire': 'FALSE',
    'Radio Type': 'Tesunho SIM TH388', 'Inv Wand Desc': '', 'Inv Wand Price': '',
    'Inv Wand Qty': '', 'Number Wand': '0', 'Number Repeater': '0',
    'DB label printed': 'FALSE',
    'All Address': 'Caitlin Mockler\r\nWelsh 2 day Enduro\r\n1 Moat Cottage \r\nBeguildy \r\nKnighton \r\nShropshire\r\nLD7 1YU\r\n\r\n07788 500295?\r\n\r\ncaitlinmockler@hotmail.com',
    'Bar Codes': '', 'Sending Status': 'Fine no problem',
    'Inv Booked Date': 'Wed 31 January 2024', 'Inv Send Out Date': 'Fri 21 June 2024',
    'Inv Due Back Date': 'Mon 1 July 2024', 'Number Wand Battery': '0',
    'Number Wand Charger': '0', 'Number Aerial Adapt': '0', 'Packed Date': '',
    'Packed Time': '', 'Unpacked Date': '', 'Unpacked Time': '',
    'Hire Sheet Printed': 'FALSE', 'ShipMe': 'FALSE', 'Missing Kit': '', 'Outbound ID': '',
    'PreShip Emailed': 'FALSE', 'To Customer': 'Welsh 2 day Enduro',
    'Has document Log': '', 'Involves Equipment': '', 'Inbound ID': ''
}, {
    'Name': 'Welwyn Garden City BID - 07/05/2024 ref 20374', 'Reference Number': '43359',
    'Booked Date': '20240124', 'Send Out Date': '20240507', 'Due Back Date': '20240515',
    'Status': 'Booked in', 'Actual Return Date': '', 'Purpose': '', 'Closed': 'FALSE',
    'Inv VHF Desc': '',
    'Delivery Address': 'Gate House\r\nFretherne Road\r\nWelwyn Garden City',
    'Number Sgl Charger': '2', 'Inv UHF Price': '11.00', 'Delivery Postcode': 'AL8 6NS',
    'Invoice': 'C:\\ProgramData\\Commence\\Commence\\8.0\\Data\\FILES\\a24632.docx',
    'Delivery Name': 'Welwyn Garden City BID',
    'Payment Terms': 'To be paid before hire date', 'Number VHF': '0', 'Number EM': '14',
    'Number VHF 6-way': '0', 'Number ICOM PSU': '0',
    'Inv UHF Desc': 'Hire of Hytera Digital walkie-talkie', 'Inv VHF Price': '',
    'Inv EM Desc': 'Hire of earpiece/microphone', 'Number Megaphone': '0',
    'Delivery Contact': 'Lee Rowark', 'Delivery Tel': '07772 590132',
    'Send / Collect': 'We send and pick up',
    'Send Method': 'Parcelforce/DB and we collect',
    'Hire Sheet Text': '\r\n* 14 x Hytera Digital radios\r\n\r\n* 2 x six-slot radio charger units\r\n\r\n* 2 x single radio charger units\r\n\r\n* 14 x Earpiece/microphones (in re-usable bags)\r\n\r\n* 5 x extra radio battery packs\r\n\r\n* 1 x Laminated walkie-talkie instruction sheet',
    'Special Kit': '', 'Return Notes': '', 'Number UHF': '14', 'Number UHF 6-way': '2',
    'Number Parrot': '0', 'Number Headset': '0', 'Delivery Ref': '',
    'Number Batteries': '5', 'Number Cases': '0', 'Delivery Description': '',
    'Inv EM Price': '1.00', 'Inv Batt Desc': 'Hire of spare battery pack',
    'Inv Batt Price': '1.00', 'Inv Parrot Desc': '', 'Inv Parrot Price': '',
    'Inv Headset Desc': '', 'Inv Headset Price': '', 'Inv Case Desc': '',
    'Inv Case Price': '', 'Inv Send Desc': 'Send Date',
    'Inv Delivery Desc': 'Delivery & Collection',
    'Inv Return Desc': 'Cust. to advise when ready for collection',
    'Delivery Cost': '35.00', 'Purchase Order': '', 'Inv EM Qty': '14',
    'Inv Headset Qty': '', 'Inv Parrot Qty': '', 'Inv Batt Qty': '5', 'Inv Case Qty': '',
    'Inv UHF Qty': '14', 'Inv VHF Qty': '', 'Discount Percentage': '',
    'Discount Description': '', 'Instruc Walkies': 'TRUE', 'Number Megaphone Bat': '0',
    'Inv Mega Qty': '', 'Inv Mega Price': '', 'Inv Mega Desc': '',
    'Inv Charger Desc': 'Radio chargers included in price', 'Inv Meg Batt Desc': '',
    'Instruc Megaphone': 'FALSE', 'Instruc Icom': 'FALSE', 'Number Icom': '0',
    'Reprogrammed': 'FALSE', 'Inv Icom Desc': '', 'Inv Icom Qty': '', 'Inv Icom Price': '',
    'Megaphone charger': 'FALSE', 'Delivery Email': 'marketing@welwyngarden.co.uk',
    'Packed By': '', 'Unpacked by': '', 'Number EMC': '0', 'Number Headset Big': '0',
    'Inv EMC Desc': '', 'Inv EMC Price': '', 'Inv EMC Qty': '', 'Inv Bighead Desc': '',
    'Inv Bighead Price': '', 'Inv Bighead Qty': '', 'Number ICOM Car Lead': '0',
    'Weeks': '1', 'Boxes': '1', 'Inv Purchase Order': '', 'Number Magmount': '0',
    'Pickup Arranged': 'FALSE', 'Number Clipon Aerial': '0', 'Recurring Hire': 'FALSE',
    'Radio Type': 'Hytera Digital', 'Inv Wand Desc': '', 'Inv Wand Price': '',
    'Inv Wand Qty': '', 'Number Wand': '0', 'Number Repeater': '0',
    'DB label printed': 'FALSE',
    'All Address': 'Lee Rowark\r\nWelwyn Garden City BID\r\nGate House\r\nFretherne Road\r\nWelwyn Garden City\r\nAL8 6NS\r\n\r\n07772 590132\r\n\r\nmarketing@welwyngarden.co.uk',
    'Bar Codes': '', 'Sending Status': 'Fine no problem',
    'Inv Booked Date': 'Wed 24 January 2024', 'Inv Send Out Date': 'Tue 7 May 2024',
    'Inv Due Back Date': 'Wed 15 May 2024', 'Number Wand Battery': '0',
    'Number Wand Charger': '0', 'Number Aerial Adapt': '0', 'Packed Date': '',
    'Packed Time': '', 'Unpacked Date': '', 'Unpacked Time': '',
    'Hire Sheet Printed': 'FALSE', 'ShipMe': 'FALSE', 'Missing Kit': '', 'Outbound ID': '',
    'PreShip Emailed': 'FALSE', 'To Customer': 'Welwyn Garden City BID',
    'Has document Log': '', 'Involves Equipment': '', 'Inbound ID': ''
}, {
    'Name': 'West Buckland School - 18/03/2024 ref 31837', 'Reference Number': '43362',
    'Booked Date': '20240112', 'Send Out Date': '20240318', 'Due Back Date': '20240327',
    'Status': 'Booked in', 'Actual Return Date': '', 'Purpose': '', 'Closed': 'FALSE',
    'Inv VHF Desc': '', 'Delivery Address': 'West Buckland\r\nBarnstaple\r\nDevon',
    'Number Sgl Charger': '0', 'Inv UHF Price': '', 'Delivery Postcode': 'EX32 0SX',
    'Invoice': '', 'Delivery Name': 'West Buckland School',
    'Payment Terms': 'To be paid before hire date', 'Number VHF': '0', 'Number EM': '0',
    'Number VHF 6-way': '0', 'Number ICOM PSU': '1', 'Inv UHF Desc': '',
    'Inv VHF Price': '', 'Inv EM Desc': '', 'Number Megaphone': '0',
    'Delivery Contact': 'Dave Price', 'Delivery Tel': '01598 760124',
    'Send / Collect': 'We send and pick up',
    'Send Method': 'Parcelforce/DB and we collect',
    'Hire Sheet Text': '\r\n\r\n* 10 x vehicle/base radios\r\n\r\n* 1 x clip-on aerials\r\n\r\n* 9 x magnetic-mount aerials\r\n\r\n* 9 x vehicle power leads\r\n\r\n* 1 x base radio mains power supplies\r\n\r\n* 1 x Laminated mobile/base radio instruc sheet',
    'Special Kit': '', 'Return Notes': '', 'Number UHF': '0', 'Number UHF 6-way': '0',
    'Number Parrot': '0', 'Number Headset': '0', 'Delivery Ref': '',
    'Number Batteries': '0', 'Number Cases': '0', 'Delivery Description': '',
    'Inv EM Price': '', 'Inv Batt Desc': '', 'Inv Batt Price': '', 'Inv Parrot Desc': '',
    'Inv Parrot Price': '', 'Inv Headset Desc': '', 'Inv Headset Price': '',
    'Inv Case Desc': '', 'Inv Case Price': '', 'Inv Send Desc': 'Send Date',
    'Inv Delivery Desc': 'Delivery & Collection',
    'Inv Return Desc': 'Cust. to advise when ready for collection',
    'Delivery Cost': '35.00', 'Purchase Order': '', 'Inv EM Qty': '',
    'Inv Headset Qty': '', 'Inv Parrot Qty': '', 'Inv Batt Qty': '', 'Inv Case Qty': '',
    'Inv UHF Qty': '', 'Inv VHF Qty': '', 'Discount Percentage': '',
    'Discount Description': '', 'Instruc Walkies': 'FALSE', 'Number Megaphone Bat': '0',
    'Inv Mega Qty': '', 'Inv Mega Price': '', 'Inv Mega Desc': '', 'Inv Charger Desc': '',
    'Inv Meg Batt Desc': '', 'Instruc Megaphone': 'FALSE', 'Instruc Icom': 'TRUE',
    'Number Icom': '10', 'Reprogrammed': 'FALSE',
    'Inv Icom Desc': 'Hire of vehicle/base radios', 'Inv Icom Qty': '10',
    'Inv Icom Price': '19.00', 'Megaphone charger': 'FALSE',
    'Delivery Email': 'dgp@westbuckland.com', 'Packed By': '', 'Unpacked by': '',
    'Number EMC': '0', 'Number Headset Big': '0', 'Inv EMC Desc': '', 'Inv EMC Price': '',
    'Inv EMC Qty': '', 'Inv Bighead Desc': '', 'Inv Bighead Price': '',
    'Inv Bighead Qty': '', 'Number ICOM Car Lead': '9', 'Weeks': '1', 'Boxes': '1',
    'Inv Purchase Order': '', 'Number Magmount': '9', 'Pickup Arranged': 'FALSE',
    'Number Clipon Aerial': '1', 'Recurring Hire': 'FALSE', 'Radio Type': 'Kirisun VHF',
    'Inv Wand Desc': '', 'Inv Wand Price': '', 'Inv Wand Qty': '', 'Number Wand': '0',
    'Number Repeater': '0', 'DB label printed': 'FALSE',
    'All Address': 'Dave Price\r\nWest Buckland School\r\nWest Buckland\r\nBarnstaple\r\nDevon\r\nEX32 0SX\r\n\r\n01598 760124\r\n\r\ndgp@westbuckland.com',
    'Bar Codes': '', 'Sending Status': 'Fine no problem',
    'Inv Booked Date': 'Fri 12 January 2024', 'Inv Send Out Date': 'Mon 18 March 2024',
    'Inv Due Back Date': 'Wed 27 March 2024', 'Number Wand Battery': '0',
    'Number Wand Charger': '0', 'Number Aerial Adapt': '0', 'Packed Date': '',
    'Packed Time': '', 'Unpacked Date': '', 'Unpacked Time': '',
    'Hire Sheet Printed': 'FALSE', 'ShipMe': 'FALSE', 'Missing Kit': '', 'Outbound ID': '',
    'PreShip Emailed': 'FALSE', 'To Customer': 'West Buckland School',
    'Has document Log': '', 'Involves Equipment': '', 'Inbound ID': ''
}]
