
CONTACT_ITEM_NAMES = ['Bezos.Jeff', 'Branson.Richard', 'Buffett.Warren', 'Carney.Steve', 'Carr.Brian',
                      'Douglas.Michael',
                      'Findlay.Howard', 'Gates.Bill', 'Jennings.Kevin', 'Logan.Andrew', 'Madison.Bruce',
                      'Malick.Charles',
                      'Mark.Kane', 'Melrose.Harry', 'Musk.Elon', 'Nadella.Satya', 'Pichai.Sundar', 'Rubbel.John',
                      'Ryder.Philip', 'Spring.Debbie', 'Steele.Patrick', 'Walsh.Peter', 'White.Peter', 'Winfrey.Oprah',
                      'Zuckerberg.Mark']
CONTACT_FIELD_NAMES = ['contactKey', 'Account', 'addModifyDate', 'addModifyUser', 'Birthday', 'busCity', 'busCountry',
                       'businessNumber', 'busState', 'busStreet', 'busZip', 'City', 'cityStateZip', 'DOB',
                       'doNotSolicit',
                       'emailBusiness', 'emailHome', 'Extension', 'FacebookLink', 'faxNumber', 'firstName',
                       'homeAddress',
                       'homeNumber', 'ID', 'Influence', 'isPrimary', 'lastContact', 'lastName', 'LinkedInLink',
                       'mailCode',
                       'mainTelephone', 'MI', 'mobileNumber', 'nextContact', 'Nickname', 'Notes', 'otherTelephone',
                       'pagerNumber', 'properName', 'Salutation', 'spouseName', 'stateProvince', 'Title', 'twitterLink',
                       'zipPostal']
JEFF_DICT = {
    'contactKey': 'Bezos.Jeff',
    'businessNumber': '1800 3000 9009',
    'Title': 'CEO of Amazon',
    'firstName': 'Jeff',
    'properName': 'Mr. Jeff Bezos',
    'lastName': 'Bezos',
    'busCity': 'Seattle',
    'busCountry': 'USA',
    'busState': 'WA',
    'busStreet': '410 Terry Ave N',
    'busZip': '98109',
    'Account': 'Amazon',
    'addModifyUser': 'Simpson.Barry.T',
    'addModifyDate': '20190815',
    'lastContact': '20190807',
    'twitterLink': 'https://twitter.com/jeffbezos',
    'FacebookLink': 'https://www.facebook.com/groups/1654560838132448/',
    'ID': '27BH1B',
    'cityStateZip': 'Seattle, WA 98109',
    'Influence': 'Low',
    'isPrimary': 'FALSE',
}
JEFF_EDITED_DICT = {
    'contactKey': 'Bezos.Geoff',
    'homeAddress': 'GEOFF',
    'businessNumber': '1800 3000 9009',
    'homeNumber': '',
    'faxNumber': '',
    'Notes': 'GEOFF',
    'Nickname': '',
    'Extension': '',
    'Title': 'CEO of Amazon',
    'mobileNumber': '',
    'pagerNumber': '',
    'Birthday': '',
    'emailHome': '',
    'firstName': 'Geoff',
    'MI': '',
    'Salutation': 'None',
    'City': '',
    'stateProvince': '',
    'zipPostal': '',
    'properName': 'Mr. Jeff Bezos',
    'spouseName': '',
    'lastName': 'Bezos',
    'emailBusiness': '',
    'doNotSolicit': 'FALSE',
    'busCity': 'Seattle',
    'busCountry': 'USA',
    'busState': 'WA',
    'busStreet': '410 Terry Ave N',
    'busZip': '98109',
    'Account': 'Amazon',
    'otherTelephone': '',
    'mainTelephone': '',
    'addModifyUser': 'Simpson.Barry.T',
    'addModifyDate': '20190815',
    'mailCode': '',
    'nextContact': '',
    'lastContact': '20190807',
    'DOB': '',
    'Relates to Activity': '',
    'Relates to Account': '',
    'Relates to Opportunity': '',
    'LinkedInLink': '',
    'Relates to mailingType': '',
    'Relates to Attachment': '',
    'twitterLink': 'https://twitter.com/jeffbezos',
    'Relates to Address': '',
    'Relates to History': '',
    'Relates to Expense': '',
    'FacebookLink': '',
    'Relates to contactType': '',
    'Relates to contactInterest': '',
    'Relates to Employee': '',
    'Handheld Device Employee': '',
    'ID': '',
    'cityStateZip': 'Seattle, WA 98109',
    'Influence': 'Low',
    'Relates to detailNote': '',
    'Manager of Contact': '',
    'Managed by Contact': '',
    'isPrimary': 'FALSE',
    'Relates to Salutation': '',
}
NEW_DICT = {
    'contactKey': 'Guy.Some',
    'businessNumber': '1800 3000 9009',
    'Title': 'CEO of SOMmeBix',
    'Notes': 'Some Notes',
    'Nickname': 'somnivkbname',
    'lastName': 'Guy',
    'firstName': 'Some',
}
NEW_DICT_RESPONSE = {
    'Account': '',
    'Birthday': '',
    'City': '',
    'DOB': '',
    'Extension': '',
    'FacebookLink': '',
    'Handheld Device Employee': '',
    'ID': '',
    'Influence': 'Low',
    'LinkedInLink': '',
    'MI': '',
    'Managed by Contact': '',
    'Manager of Contact': '',
    'Nickname': 'somnivkbname',
    'Notes': 'Some Notes',
    'Relates to Account': '',
    'Relates to Activity': '',
    'Relates to Address': '',
    'Relates to Attachment': '',
    'Relates to Employee': '',
    'Relates to Expense': '',
    'Relates to History': '',
    'Relates to Opportunity': '',
    'Relates to Salutation': '',
    'Relates to contactInterest': '',
    'Relates to contactType': '',
    'Relates to detailNote': '',
    'Relates to mailingType': '',
    'Salutation': 'None',
    'Title': 'CEO of SOMmeBix',
    'addModifyDate': '',
    'addModifyUser': '',
    'busCity': '',
    'busCountry': '',
    'busState': '',
    'busStreet': '',
    'busZip': '',
    'businessNumber': '1800 3000 9009',
    'cityStateZip': '',
    'contactKey': 'Some.Guy',
    'doNotSolicit': 'FALSE',
    'emailBusiness': '',
    'emailHome': '',
    'faxNumber': '',
    'firstName': '',
    'homeAddress': '',
    'homeNumber': '',
    'isPrimary': 'FALSE',
    'lastContact': '20240629',
    'lastName': '',
    'mailCode': '',
    'mainTelephone': '',
    'mobileNumber': '',
    'nextContact': '',
    'otherTelephone': '',
    'pagerNumber': '',
    'properName': '',
    'spouseName': '',
    'stateProvince': '',
    'twitterLink': '',
    'zipPostal': '',
}
UPDATE_DICT = {
    'businessNumber': '9999 8888 7777',
    'Title': 'TEST UPDATE DICT TITLE',
    'Notes': 'TEST UPDATE DICT NOTES',
}
JEFF_KEY = JEFF_DICT.get('contactKey')
FNAME = NEW_DICT.get('firstName')
LNAME = NEW_DICT.get('lastName')
NEW_KEY = NEW_DICT.get('contactKey')
TEST_ITEM_NAME = 'TestItem'
# TEST_ITEM_NAME = 'TestItem' + threading.current_thread().name + datetime.now().strftime('%Y-%m-%d-%H-%M-%S')
